/**
 * Helpers for `cards view` rendering (#2228).
 *
 * formatCommentForView: auto-generated comments (blast-radius, domain-radius)
 * render as one-line summaries by default; user-authored comments render full.
 * verbose=true renders everything full.
 */

// Auto-generated comment prefixes. These come from cards CLI automation
// (blast-radius.ts formatBlastComment, domain-radius warning in sdk.ts).
// Pattern: comment first line starts with one of these markers.
const AUTO_GENERATED_PREFIXES = [
  '**Blast Radius**',
  '**Domain Radius**',
];

function isAutoGenerated(text: string): boolean {
  if (!text) return false;
  const firstLine = text.split('\n', 1)[0];
  return AUTO_GENERATED_PREFIXES.some((p) => firstLine.startsWith(p));
}

export function formatCommentForView(text: string, verbose: boolean): string {
  if (!text) return '';
  if (verbose) return text;

  if (!isAutoGenerated(text)) return text;

  // Auto-generated, not verbose — truncate to first line + hint if there's
  // hidden content. Single-line comments get no hint (nothing hidden).
  const lines = text.split('\n');
  if (lines.length <= 1) return text;
  const hidden = lines.length - 1;
  return `${lines[0]}\n  (use --verbose for full — ${hidden} more line${hidden === 1 ? '' : 's'})`;
}
