//! #1889 — Session start must regenerate Pulse before writing context
//! Bug: roles boot with stale pulse-latest.json from previous session,
//! report dead index sources that were already fixed.

use std::fs;
use std::path::Path;

const SHIM: &str = "/Users/jeffbridwell/CascadeProjects/chorus/platform/services/chorus-hooks/target/release/chorus-hook-shim";

/// Session-start regenerates pulse-latest.json with fresh data
#[test]
fn session_start_regenerates_pulse() {
    // Write a poison pulse file with known stale content
    let stale_pulse = r#"{"timestamp":"2020-01-01T00:00:00","stale_marker":true,"index_freshness":{"dead":99}}"#;
    fs::write("/tmp/pulse-latest.json", stale_pulse).expect("should write stale pulse");

    // Run session-start
    let output = std::process::Command::new(SHIM)
        .args(["session-start", "silas"])
        .output()
        .expect("session-start should execute");

    assert!(output.status.success(), "session-start should succeed");

    // Pulse file should have been regenerated — stale_marker gone
    let content = fs::read_to_string("/tmp/pulse-latest.json")
        .expect("pulse-latest.json should exist after session-start");
    assert!(
        !content.contains("stale_marker"),
        "pulse-latest.json should be regenerated by session-start, not stale. Got: {}",
        &content[..content.len().min(200)]
    );
}

/// Pulse regenerated by session-start has fresh index_freshness (not from cache)
#[test]
fn session_start_pulse_has_fresh_freshness() {
    // Run session-start
    let _ = std::process::Command::new(SHIM)
        .args(["session-start", "silas"])
        .output();

    let content = fs::read_to_string("/tmp/pulse-latest.json")
        .expect("pulse-latest.json should exist");
    let v: serde_json::Value = serde_json::from_str(&content)
        .expect("pulse should be valid JSON");

    // Timestamp should be recent (within last 30 seconds)
    let ts = v.get("timestamp").and_then(|t| t.as_str()).unwrap_or("");
    assert!(
        !ts.is_empty() && !ts.starts_with("2020"),
        "pulse timestamp should be current, got: {}",
        ts
    );

    // index_freshness should exist and not show dead:99 (our poison value)
    let freshness = v.get("index_freshness").expect("must have index_freshness");
    let dead = freshness.get("dead").and_then(|d| d.as_u64()).unwrap_or(0);
    assert!(
        dead != 99,
        "index_freshness should be live data, not stale poison value"
    );
}
