//! #4432 — Abby's Gemini asks Jeff to approve every tool call; ours ask for
//! none. Jeff 2026-10-06 08:41: approving her tool calls "is a big blocker".
//! Her allowed tools are generated from the same allow rules the Claude roles
//! run under (`permissions.allow` in the Claude settings file), one source,
//! read at every session start, so the two lists cannot drift. The Chorus
//! guard hook (BeforeTool → chorus-hook-shim runtime-hook gemini) still makes
//! the real refusals; this only stops the per-call approval prompt.

use crate::Result;
use serde_json::Value;
use std::path::Path;

/// One Claude allow rule → the Gemini 0.62 tool names it covers. `None` when
/// Gemini has no such tool (the rule is reported, never guessed).
fn gemini_names(rule: &str) -> Option<Vec<String>> {
    let (tool, arg) = match rule.split_once('(') {
        Some((t, rest)) => (t, rest.strip_suffix(')').map(|a| a.trim_end_matches('*').trim_end_matches(':'))),
        None => (rule, None),
    };
    let all = |names: &[&str]| Some(names.iter().map(|n| n.to_string()).collect());
    match tool {
        "Read" => all(&["read_file", "read_many_files", "list_directory"]),
        "Glob" => all(&["glob"]),
        "Grep" => all(&["grep_search"]),
        "Write" => all(&["write_file"]),
        "Edit" => all(&["replace"]),
        "WebFetch" => all(&["web_fetch"]),
        "WebSearch" => all(&["google_web_search"]),
        "Skill" => all(&["activate_skill"]),
        "Task" => all(&["invoke_agent"]),
        "Bash" => match arg {
            None | Some("") => all(&["run_shell_command"]),
            Some(prefix) => Some(vec![format!("run_shell_command({})", prefix.trim_end())]),
        },
        t if t.starts_with("mcp__") => {
            let server = t.trim_start_matches("mcp__").split("__").next().unwrap_or("");
            (!server.is_empty()).then(|| vec![format!("mcp_{server}_*")])
        }
        _ => None,
    }
}

/// The Gemini allowed list for a Claude settings document, plus the rules
/// that have no Gemini tool. Order follows the source; duplicates dropped.
pub fn gemini_allowed(claude_settings: &Value) -> Result<(Vec<String>, Vec<String>)> {
    let rules = claude_settings
        .pointer("/permissions/allow")
        .and_then(Value::as_array)
        .ok_or("the Claude settings have no permissions.allow list")?;
    let (mut allowed, mut unmapped) = (Vec::new(), Vec::new());
    for rule in rules.iter().filter_map(Value::as_str) {
        match gemini_names(rule) {
            Some(names) => {
                for n in names {
                    if !allowed.contains(&n) {
                        allowed.push(n);
                    }
                }
            }
            None => unmapped.push(rule.to_string()),
        }
    }
    if allowed.is_empty() {
        return Err("the Claude allow rules map to no Gemini tool".into());
    }
    Ok((allowed, unmapped))
}

/// The Gemini policy file (TOML, user tier) for an allowed list: one allow
/// rule for the plain tool names, one per shell command prefix. Gemini 0.62
/// marks `tools.allowed` in settings.json deprecated (removed at 1.0), so the
/// list is written as policy, the form it keeps.
pub fn gemini_policy_toml(allowed: &[String], source: &Path) -> String {
    let q = |v: &str| serde_json::to_string(v).unwrap_or_default();
    let mut plain = Vec::new();
    let mut out = format!(
        "# GENERATED by chorus-agent (#4432) from the Claude allow rules in {}.\n# Rewritten at every Gemini session start; edit the source, not this file.\n",
        source.display()
    );
    let mut prefixes = Vec::new();
    for name in allowed {
        match name.strip_prefix("run_shell_command(").and_then(|r| r.strip_suffix(')')) {
            Some(prefix) => prefixes.push(prefix.to_string()),
            None => plain.push(q(name)),
        }
    }
    out.push_str(&format!("\n[[rule]]\ntoolName = [{}]\ndecision = \"allow\"\npriority = 100\n", plain.join(", ")));
    for prefix in prefixes {
        out.push_str(&format!(
            "\n[[rule]]\ntoolName = \"run_shell_command\"\ncommandPrefix = {}\ndecision = \"allow\"\npriority = 100\n",
            q(&prefix)
        ));
    }
    out
}

/// Writes the allowed list as `<home>/.gemini/policies/chorus-allowed.toml`
/// (atomic replace). Returns the list written and the rules left unmapped.
pub fn install_gemini_allowed(source: &Path, home: &Path) -> Result<(Vec<String>, Vec<String>)> {
    let text = std::fs::read_to_string(source)
        .map_err(|e| format!("cannot read the allow rules at {}: {e}", source.display()))?;
    let claude: Value = serde_json::from_str(&text)
        .map_err(|e| format!("the allow rules at {} are not JSON: {e}", source.display()))?;
    let (allowed, unmapped) = gemini_allowed(&claude)?;
    let dir = home.join(".gemini/policies");
    std::fs::create_dir_all(&dir).map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
    let target = dir.join("chorus-allowed.toml");
    let tmp = dir.join("chorus-allowed.toml.tmp");
    std::fs::write(&tmp, gemini_policy_toml(&allowed, source)).map_err(|e| format!("cannot write {}: {e}", tmp.display()))?;
    std::fs::rename(&tmp, &target).map_err(|e| format!("cannot replace {}: {e}", target.display()))?;
    Ok((allowed, unmapped))
}
