//! Demo Provenance (#1670)
//!
//! PostToolUse hook after /demo skill completes.
//! Auto-generates a demo brief to Wren's inbox so the builder
//! can't skip the paper trail.

use crate::types::{HookInput, HookResponse};
use std::process::Command;
use tracing::info;

const BOARD_TS: &str = "/Users/jeffbridwell/CascadeProjects/messages/scripts/board-ts";
const BRIEFS_DIR: &str = "/Users/jeffbridwell/CascadeProjects/product-manager/briefs";
const CHORUS_LOG: &str = "/Users/jeffbridwell/CascadeProjects/messages/scripts/chorus-log.sh";

/// PostToolUse: after /demo skill completes, generate the demo brief
pub async fn check(input: &HookInput) -> HookResponse {
    let skill = input.get_tool_input_str("skill");
    if skill != "demo" {
        return HookResponse::allow();
    }

    let args = input.get_tool_input_str("args");
    let card_id = extract_card_id(&args);
    if card_id.is_empty() {
        return HookResponse::allow();
    }

    let role = input.role();

    // Get card info
    let (title, owner) = get_card_info(&card_id);

    // Check if brief already exists (builder may have written one manually)
    let date = chrono::Utc::now().format("%Y-%m-%d").to_string();
    let brief_path = format!("{}/{}-demo-{}.md", BRIEFS_DIR, date, card_id);
    if std::path::Path::new(&brief_path).exists() {
        info!(card = %card_id, "demo-provenance: brief already exists, skipping");
        return HookResponse::allow();
    }

    // Generate brief
    let brief = format!(
        "# Demo ready: #{card_id}\n\n\
         **Builder:** {owner}\n\
         **Smoke check:** PASS\n\
         **Card:** {title}\n\
         **Demo initiated by:** {role}\n\
         **Timestamp:** {ts}\n\n\
         Auto-generated by demo-provenance hook.\n\
         Ready for Jeff + Wren review.\n",
        card_id = card_id,
        owner = if owner.is_empty() { role.as_str() } else { &owner },
        title = if title.is_empty() { "unknown" } else { &title },
        role = role.as_str(),
        ts = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ"),
    );

    if std::fs::write(&brief_path, &brief).is_ok() {
        info!(card = %card_id, path = %brief_path, "demo-provenance: brief generated");

        // Emit spine event
        let _ = Command::new(CHORUS_LOG)
            .args(["card.demo.completed", role.as_str(), &format!("card={}", card_id)])
            .output();

        return HookResponse::warn_stderr(&format!(
            "Demo brief auto-generated: {}",
            brief_path.rsplit('/').next().unwrap_or(&brief_path)
        ));
    }

    HookResponse::allow()
}

fn extract_card_id(args: &str) -> String {
    args.split_whitespace()
        .find(|s| s.chars().all(|c| c.is_ascii_digit()))
        .unwrap_or("")
        .to_string()
}

fn get_card_info(card_id: &str) -> (String, String) {
    let output = Command::new("bash")
        .args([BOARD_TS, "view", card_id])
        .output();

    match output {
        Ok(o) if o.status.success() => {
            let stdout = String::from_utf8_lossy(&o.stdout);
            let title = stdout.lines().next()
                .and_then(|l| l.split(&format!("#{} ", card_id)).nth(1))
                .unwrap_or("")
                .to_string();
            let owner = stdout.lines()
                .find(|l| l.contains("Owner:"))
                .and_then(|l| l.split("Owner:").nth(1))
                .map(|s| s.trim().to_lowercase())
                .unwrap_or_default();
            (title, owner)
        }
        _ => (String::new(), String::new()),
    }
}
