#!/usr/bin/env bats
# @test-type: integration — runs the scan with every live input stubbed (needs the personal-site checkout)
# @domain: analytics — the product domain this suite guards (#4334)
# Tests for daily-signal-scan.sh (#2088)
# What Jeff sees: a brief ready by 6am with codebase weather, trust verification,
# backlog coherence, and golfball detection. No session required.
#
# #4336 — why this suite hung past 120s: every case ran the whole scan against
# the live box, and one scan is ~40s (deep-health.sh 22s, eslint over the
# personal site 14s, two `cards list` calls, jest --listTests). Six cases, four
# minutes. Now every slow or live input is a stub, each scan is capped at 60s
# (perl alarm — macOS has no `timeout`), and the section checks assert the
# exact lines the stubs make the scan write, not any word that happens to match.
#
# The seams, none of which change the script:
#   CHORUS_ROOT          → a fake root: deep-health.sh stub, decisions.md/projects.md
#   DAILY_SIGNAL_CARDS   → a board stub printing a fixed board
#   HOME                 → a fake home holding the pulse hooks.log
#   npx                  → an exported bash function (the script resets PATH, so a
#                          PATH stub cannot reach it; a function is looked up first)
# The one thing left real is `git log` in the personal-site checkout the script
# hardcodes; without that checkout the scan cannot run and the suite says so.

# #3369: resolve relative to this repo (werk or canonical), not a hardcoded
# canonical path — the old pin made in-werk runs test the UNFIXED main copy.
SCRIPT="$(cd "$(dirname "$BATS_TEST_FILENAME")/../scripts" && pwd)/daily-signal-scan.sh"
PERSONAL_SITE="${PERSONAL_SITE:-$HOME/CascadeProjects/jeff-bridwell-personal-site}"

setup() {
  [ -d "$PERSONAL_SITE" ] || skip "UNMEASURED — the scan hardcodes the personal-site checkout, absent here (#4336)"
  T="$BATS_TEST_TMPDIR"
  OUT="$T/signal.md"
  # fake root
  mkdir -p "$T/root/platform/scripts" "$T/root/roles/wren" "$T/root/roles/silas" "$T/root/roles/kade"
  printf '#!/bin/bash\necho "deep-health: stub ok"\n' > "$T/root/platform/scripts/deep-health.sh"
  : > "$T/root/roles/wren/decisions.md"
  : > "$T/root/roles/wren/projects.md"
  touch -t 202001010000 "$T/root/roles/wren/projects.md"
  # fake home: two deny and one allow today
  mkdir -p "$T/home/Library/Logs/Gathering"
  today=$(TZ=America/New_York date '+%Y-%m-%d')
  {
    printf '%s 06:00:00 | a | b | c | gate-alpha | deny\n' "$today"
    printf '%s 06:01:00 | a | b | c | gate-alpha | deny\n' "$today"
    printf '%s 06:02:00 | a | b | c | gate-beta | allow\n' "$today"
  } > "$T/home/Library/Logs/Gathering/hooks.log"
  # boards
  printf 'WIP (2):\n  4336  replace source greps [kade] type:fix domain:tests\n  4335  hollow checks [kade] type:new domain:tests\nNext (0):\nDone (1):\n  4000  old [wren]\n' > "$T/board-full.txt"
  printf 'WIP (0):\nNext (1):\n  4001  a thing [wren] type:fix domain:x\nDone (0):\n' > "$T/board-empty-wip.txt"
  board full
  npx() {
    case "$*" in
      *"jest --listTests"*) printf '/x/a.test.ts\n/x/b.test.ts\n/x/c.test.ts\n' ;;
      *eslint*) echo "✖ 5 problems (0 errors, 5 warnings)" ;;
    esac
  }
  export -f npx
}

# board <full|empty-wip> — which board the cards stub prints
board() {
  printf '#!/bin/bash\n[ "$1" = list ] && cat "%s"\n' "$T/board-$1.txt" > "$T/cards"
}

# scan [script] — run the scan, stubbed, capped at 60s
scan() {
  local script="${1:-$SCRIPT}"
  run env HOME="$T/home" CHORUS_ROOT="$T/root" DAILY_SIGNAL_CARDS="${CARDS_OVERRIDE:-$T/cards}" \
    perl -e 'alarm shift; exec @ARGV' 60 bash "$script" --dry-run --output "$OUT"
}

@test "AC8: script exists and is executable" {
  [ -x "$SCRIPT" ]
}

@test "AC8: produces output file" {
  scan
  [ "$status" -eq 0 ]
  [ -f "$OUT" ]
  grep -q "^# Daily Signal — " "$OUT"
  # the brief is finished, not cut off part way
  grep -q "^\*Auto-generated by daily-signal-scan.sh (#2088)\*$" "$OUT"
}

@test "AC1: output includes codebase weather section" {
  scan
  grep -q "^## Codebase Weather$" "$OUT"
  grep -q "^- \*\*Test files:\*\* 3$" "$OUT"
  grep -q "^- \*\*Lint warnings:\*\* 5$" "$OUT"
}

@test "AC2: output includes trust verification section" {
  scan
  grep -q "^## Trust Verification$" "$OUT"
  grep -q "^- \*\*Gate decisions (24h):\*\* 1 allow, 2 deny$" "$OUT"
  grep -q "^  - gate-alpha (2)$" "$OUT"
  grep -q "^- \*\*Deep health:\*\* deep-health: stub ok$" "$OUT"
}

@test "AC4: output includes doc freshness section" {
  scan
  grep -q "^## Doc Freshness$" "$OUT"
  grep -q "^- \*\*decisions.md:\*\* 0h old — fresh$" "$OUT"
  grep -q "^- \*\*projects.md:\*\* [0-9]*h old — STALE$" "$OUT"
}

@test "AC5: output includes flow health section" {
  scan
  grep -q "^## Flow Health$" "$OUT"
  grep -q "^- \*\*WIP:\*\* 2 cards$" "$OUT"
  grep -q "^  - 4336  replace source greps" "$OUT"
  grep -q "^- \*\*Next queue:\*\* empty$" "$OUT"
  # AC7 rides the same board: a fix card next to new work in one domain
  grep -q "^  - \*\*domain:tests:\*\* 1 fix/swat in WIP+Next alongside active development$" "$OUT"
}

# #4274 — an empty WIP section killed the scan under its own `set -euo pipefail`.
# Both cases run the scan on a board with nothing in WIP.
@test "NEGATIVE PROOF (#4274): '[ -n ] && echo' as a loop body ends the scan on an empty section" {
  # A copy of the scan with the #4274 fix undone, on the empty-WIP board: it
  # must fail to finish. This is what makes the next case able to go red.
  board empty-wip
  sed 's/if \[ -n "\$line" \]; then echo "  - \$line"; fi/[ -n "$line" ] \&\& echo "  - $line"/' "$SCRIPT" > "$T/scan-unfixed.sh"
  run grep -c '\[ -n "\$line" \] && echo' "$T/scan-unfixed.sh"
  [ "$output" -ge 1 ]
  scan "$T/scan-unfixed.sh"
  [ "$status" -ne 0 ]
  run grep -q "^## Golfball Detection$" "$OUT"
  [ "$status" -ne 0 ]
}

@test "#4274: the if-form prints nothing for an empty section and the scan continues" {
  board empty-wip
  scan
  [ "$status" -eq 0 ]
  grep -q "^- \*\*WIP:\*\* 0 cards$" "$OUT"
  grep -q "^- \*\*Next queue:\*\* 1 cards$" "$OUT"
  grep -q "^## Golfball Detection$" "$OUT"
  grep -q "^\*Auto-generated by daily-signal-scan.sh (#2088)\*$" "$OUT"
}

# #4334 — an unreadable board ended the brief under `set -e`. The scan must
# finish and say the section was not measured.
@test "#4334: an unreadable board still finishes the brief and says flow health was not measured" {
  CARDS_OVERRIDE=/usr/bin/false scan
  [ "$status" -eq 0 ]
  grep -q "flow health not measured" "$OUT"
  grep -q "^  - board unreadable — not measured$" "$OUT"
  grep -q "^\*Auto-generated by daily-signal-scan.sh (#2088)\*$" "$OUT"
}
