#!/usr/bin/env bash
# Demo Provenance — owned by /demo product (Wren)
# Contract: takes card_id and role as args
# Generates demo brief to wren/briefs/, emits spine event
# stderr = status message

set -euo pipefail

CHORUS_ROOT="${CHORUS_ROOT:-$(cd "$(dirname "$0")/../../../.." && pwd)}"
CARDS="$CHORUS_ROOT/platform/scripts/cards"
CHORUS_LOG="$CHORUS_ROOT/platform/scripts/chorus-log"
BRIEF_DIR="$CHORUS_ROOT/platform/roles/wren/briefs"

CARD_ID="${1:-}"
ROLE="${2:-wren}"

if [ -z "$CARD_ID" ]; then
  echo "provenance: no card_id provided" >&2
  exit 1
fi

# Get card details
CARD_VIEW=$("$CARDS" view "$CARD_ID" 2>&1) || true
if echo "$CARD_VIEW" | head -1 | grep -q "^ERROR"; then
  echo "provenance: card #${CARD_ID} not found" >&2
  exit 1
fi

TITLE=$(echo "$CARD_VIEW" | head -1 | sed 's/^#[0-9]* //')
OWNER=$(echo "$CARD_VIEW" | grep "Owner:" | sed 's/.*Owner:\s*//' | tr -d ' ')
AC_LINES=$(echo "$CARD_VIEW" | grep -E '^\s*- \[' || true)
AC_TOTAL=$(echo "$AC_LINES" | grep -c '^\s*- \[' 2>/dev/null | tr -d '\n' || printf '0')
AC_CHECKED=$(echo "$AC_LINES" | grep -c '^\s*- \[x\]' 2>/dev/null | tr -d '\n' || printf '0')
DATE=$(TZ=America/New_York date '+%Y-%m-%d')
TIMESTAMP=$(TZ=America/New_York date '+%Y-%m-%dT%H:%M')

# Generate demo brief
BRIEF_FILE="$BRIEF_DIR/${DATE}-demo-${CARD_ID}.md"
cat > "$BRIEF_FILE" << EOF
# Demo ready: #${CARD_ID} — ${TITLE}

**Builder:** ${OWNER}
**Demo initiated by:** ${ROLE}
**Timestamp:** ${TIMESTAMP}

## AC Status (${AC_CHECKED}/${AC_TOTAL})
${AC_LINES}

Auto-generated by /demo provenance gate.
EOF

# Emit spine event
"$CHORUS_LOG" card.demo.started "$ROLE" card="$CARD_ID" 2>/dev/null || true

# Log demo on the board
"$CARDS" demo "$CARD_ID" >/dev/null 2>&1 || true

echo "provenance: brief written to ${BRIEF_FILE}, spine event emitted" >&2
exit 0
