import * as fs from 'fs';
import { RoleConfig } from './config';
import { ConversationTurn } from './context-assembler';
import { writeBrief } from './pod-brief-io';
import { log } from './logger';

/**
 * Patterns that indicate a role is committing to do something.
 * Matched against the raw response text (before formatting is stripped).
 */
const COMMITMENT_PATTERNS: RegExp[] = [
  /\bI'll\b/i,
  /\bI will\b/i,
  /\bI'm going to\b/i,
  /\bStarting now\b/i,
  /\bI'll build\b/i,
  /\bI'll add\b/i,
  /\bI'll ship\b/i,
  /\bI'll create\b/i,
  /\bI'll write\b/i,
  /\bI'll audit\b/i,
  /\bI'll check\b/i,
  /\bI'll review\b/i,
  /\bI'll fix\b/i,
  /\bI'll update\b/i,
  /\bI'll implement\b/i,
  /\bcommit(ting)? to\b/i,
  /\bwhat I'm building\b/i,
  /\bwhat I'll build\b/i,
  /\bmy next step\b/i,
  /\bnext steps?\b/i,
];

/**
 * Extract sentences that contain commitment language from a response.
 */
function extractCommitments(text: string): string[] {
  const sentences = text.split(/(?<=[.!?])\s+/);
  const commitments: string[] = [];

  for (const sentence of sentences) {
    if (COMMITMENT_PATTERNS.some(p => p.test(sentence))) {
      commitments.push(sentence.trim());
    }
  }

  return commitments;
}

/**
 * After a group conversation, write a brief to each role that made
 * commitments. The brief lands in their briefs/ directory and gets
 * picked up by team-scan.sh on their next session start.
 */
export async function writeCommitmentBriefs(
  triggerText: string,
  channelName: string,
  turns: ConversationTurn[],
  allRoles: RoleConfig[]
): Promise<void> {
  const dateStr = new Date().toISOString().split('T')[0];
  const timeStr = new Date().toISOString().split('T')[1].slice(0, 5).replace(':', '');

  for (const turn of turns) {
    const commitments = extractCommitments(turn.text);
    if (commitments.length === 0) continue;

    // Find this role's config to get briefsPath
    const roleConfig = allRoles.find(r => r.name === turn.roleName);
    if (!roleConfig) continue;

    // Build the brief
    const otherTurns = turns
      .filter(t => t.roleName !== turn.roleName)
      .map(t => `**${t.roleName}:** ${t.text}`)
      .join('\n\n');

    const brief = [
      `# Conversation Commitment — ${dateStr}`,
      '',
      `**Source:** Group conversation in #${channelName}`,
      `**Trigger:** ${triggerText.slice(0, 200)}`,
      `**Participants:** ${turns.map(t => t.roleName).join(', ')}`,
      '',
      '## Your commitments from this conversation',
      '',
      ...commitments.map(c => `- ${c}`),
      '',
      '## Full conversation context',
      '',
      `**${turn.roleName} (you):** ${turn.text}`,
      '',
      otherTurns,
      '',
      '---',
      '*Auto-generated by bridge from group conversation. Pick this up in your next session.*',
    ].join('\n');

    // Write to the role's briefs directory (filesystem + pod best-effort)
    const filename = `${dateStr}-conversation-commitment-${timeStr}.md`;

    try {
      await writeBrief(roleConfig, filename, brief);
      log('info', `Commitment brief written for ${turn.roleName}`, {
        event: 'commitment_brief',
        role: turn.roleName,
        filename,
        commitmentCount: commitments.length,
      });

      // Append a nudge to the running log Jeff checks
      appendNudge(turn.roleName, channelName, commitments[0]);
    } catch (err) {
      log('error', `Failed to write commitment brief for ${turn.roleName}: ${err}`, {
        filename,
      });
    }
  }
}

/**
 * Append a one-liner to the nudge log. Jeff reads this file and
 * copy-pastes the nudge into each role's session.
 */
const NUDGE_LOG = '/team/nudges/nudges.md';

function appendNudge(roleName: string, channel: string, firstCommitment: string): void {
  const now = new Date();
  const time = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: false });
  const displayName = roleName.charAt(0).toUpperCase() + roleName.slice(1);
  const short = firstCommitment.slice(0, 80).replace(/\n/g, ' ');
  const line = `- [ ] **${displayName}**: check your briefs — "${short}" (${channel}, ${time})\n`;

  try {
    // Create file with header if it doesn't exist
    if (!fs.existsSync(NUDGE_LOG)) {
      fs.writeFileSync(NUDGE_LOG, '# Nudges\n\nCopy-paste these into each role\'s session, then delete the line.\n\n');
    }
    fs.appendFileSync(NUDGE_LOG, line, 'utf-8');
    log('info', `Nudge appended for ${roleName}`);
  } catch (err) {
    log('error', `Failed to append nudge for ${roleName}: ${err}`);
  }
}
