/**
 * #3420 — page-level smoke test for the GENERATED Athena domain page.
 * chorus-api serves the owl-api-emitted shell (public/domain.html) + its renderer
 * + system.css from the '/' static mount. This proves the SHELL anatomy is intact
 * and the assets load — the contract between the generator (owl-api page_html) and
 * the runtime that serves it. Hermetic: in-process harness, no live :3340.
 */
import { startTestApp, TestApp } from './lib/test-app';

let harness: TestApp;
beforeAll(async () => { harness = await startTestApp(); });
afterAll(async () => { await harness.close(); });

describe('#3420 generated domain page — smoke', () => {
  test('GET /domain.html serves the generated shell with the full anatomy', async () => {
    const res = await fetch(`${harness.baseUrl}/athena/domain-detail.html`);
    expect(res.status).toBe(200);
    const html = await res.text();

    // it is the GENERATED projection, not a hand-edited page
    expect(html).toContain('GENERATED by owl-api page_html');

    // #3415 system.css vocabulary + theme
    expect(html).toContain('/css/system.css');
    expect(html).toContain('class="theme-light"');
    expect(html).toContain('class="wrap"');

    // the mount-point anatomy the renderer fills (breadcrumb -> identity -> stats -> part-of -> promise -> completeness -> facets)
    for (const id of [
      'bc-step', 'bc-domain', 'domain-title', 'domain-subtitle',
      'stats-bar', 'partof-block', 'haschild-block', 'promise-block', 'completeness-block', 'content-sections',
    ]) {
      expect(html).toContain(`id="${id}"`);
    }

    // the data-route security decision is RECORDED in the artifact (AC4), not just in conversation
    expect(html).toContain('DATA-ROUTE SECURITY DECISION');

    // the renderer is wired + the owl-api port is injected (not hardcoded in the JS)
    expect(html).toContain('window.OWL_PORT = 3360');
    expect(html).toContain('/js/domain-renderer.js');
  });

  test('the renderer asset loads from the same origin', async () => {
    const res = await fetch(`${harness.baseUrl}/js/domain-renderer.js`);
    expect(res.status).toBe(200);
    const js = await res.text();
    expect(js).toContain('domain-renderer.js');
    expect(js).toContain('FACETS');
    expect(js).toContain('partOfHtml');   // AC2 upward builder is shipped
    expect(js).toContain('hasChildHtml');  // #3351 downward structural builder is shipped
  });

  test('the system.css design system loads from the same origin', async () => {
    const res = await fetch(`${harness.baseUrl}/css/system.css`);
    expect(res.status).toBe(200);
  });

  test('#3351 retirement gate — the old hand-built renderer is gone', async () => {
    // the canonical page now loads the shared generated renderer, not the 76KB hand-built one
    const page = await (await fetch(`${harness.baseUrl}/athena/domain-detail.html`)).text();
    expect(page).toContain('/js/domain-renderer.js');
    expect(page).not.toContain('domain-detail.js');
    // and the old renderer asset is retired (404), not still served
    const old = await fetch(`${harness.baseUrl}/athena/domain-detail.js`);
    expect(old.status).toBe(404);
  });
});
