/**
 * #3420/#3351 — page-level smoke test for the GENERATED Athena domain page.
 * chorus-api serves the owl-api-emitted shell (public/domain.html) + its renderer
 * + system.css from the '/' static mount. Proves the SHELL anatomy is intact (incl. the
 * #3351 child-domains fold mount) and the assets load. Hermetic: in-process harness.
 */
import { startTestApp, TestApp } from './lib/test-app';

let harness: TestApp;
beforeAll(async () => { harness = await startTestApp(); });
afterAll(async () => { await harness.close(); });

describe('#3420 generated domain page — smoke', () => {
  test('GET /domain.html serves the generated shell with the full anatomy', async () => {
    const res = await fetch(`${harness.baseUrl}/domain.html`);
    expect(res.status).toBe(200);
    const html = await res.text();
    expect(html).toContain('GENERATED by owl-api page_html');
    expect(html).toContain('/css/system.css');
    expect(html).toContain('class="theme-light"');
    expect(html).toContain('class="wrap"');
    for (const id of [
      'bc-step', 'bc-domain', 'domain-title', 'domain-subtitle',
      'stats-bar', 'partof-block', 'haschild-block', 'promise-block', 'completeness-block', 'content-sections',
    ]) {
      expect(html).toContain(`id="${id}"`);
    }
    expect(html).toContain('DATA-ROUTE SECURITY DECISION');
    expect(html).toContain('window.OWL_PORT = 3360');
    expect(html).toContain('/js/domain-renderer.js');
  });

  test('the renderer asset loads from the same origin', async () => {
    const res = await fetch(`${harness.baseUrl}/js/domain-renderer.js`);
    expect(res.status).toBe(200);
    const js = await res.text();
    expect(js).toContain('domain-renderer.js');
    expect(js).toContain('childTreeHtml');   // #3351 recursive composition tree builder is shipped
  });

  test('the system.css design system loads from the same origin', async () => {
    const res = await fetch(`${harness.baseUrl}/css/system.css`);
    expect(res.status).toBe(200);
  });
});
