// @test-type: unit
// #3627 — the committed generated pages must speak to the LIVE data surface.
// #3603 retired /api/athena/<collection> on :3340; the committed shells predated
// that and entity-renderer.js still fetched the dead route — the 404 was
// swallowed and rendered as "No instances in the model" while athena-make held
// 7 value streams, 4 products, 55 domains. These are string-level drift guards
// (same style as no-3000-pagerefs-3361): the shells carry the OWL_PORT the
// generator emits, the renderer builds its base from it, and a fetch failure
// can never masquerade as an empty model.
import * as fs from 'fs';
import * as path from 'path';

const PUB = path.join(__dirname, '..', 'public');
const read = (p: string): string => fs.readFileSync(path.join(PUB, p), 'utf-8');

// #3635 replaced the athena/ generated skeletons with the Jeff-approved hand-
// authored family (pending the generator upgrade); those pages carry the #3635
// marker + athena-flow.js wiring instead of the page_html header. domain.html
// (root) remains a generated shell.
const GENERATED_SHELLS = ['domain.html'];
const FAMILY_PAGES = ['athena/value-stream.html', 'athena/product.html',
  'athena/products.html', 'athena/domains.html', 'athena/domain.html'];

describe('#3627 generated shells are current-generation (OWL_PORT wired)', () => {
  for (const shell of GENERATED_SHELLS) {
    it(`${shell} injects window.OWL_PORT (stale pre-#3603 shells lacked it)`, () => {
      const html = read(shell);
      expect(html).toContain('window.OWL_PORT = 3360');
      // #4004 — the generator was RENAMED owl-api -> athena-make (#3561); the
      // pages it had already emitted still carry the old banner, and no
      // regeneration has happened since. Assert the invariant that matters —
      // this page is a GENERATED PROJECTION, never hand-authored — without
      // pinning the generator's current name, which is what made a rename read
      // as a broken page. A hand-written page still fails: it carries no
      // GENERATED banner at all.
      expect(html).toMatch(/GENERATED by (athena-make|owl-api) page_html/);
    });
  }
  for (const page of FAMILY_PAGES) {
    it(`${page} (#3635 family) wires OWL_PORT + the shared live-fetch runtime`, () => {
      const html = read(page);
      expect(html).toContain('window.OWL_PORT = 3360');
      expect(html).toContain('athena-flow.js');
      expect(html).toContain('#3635');
    });
  }
});

describe('#3627 entity-renderer speaks athena-make, not the retired athena route', () => {
  const js = () => read('js/entity-renderer.js');

  it('builds its API base from OWL_PORT (athena-make), not a hardcoded /api/athena', () => {
    expect(js()).toContain('window.OWL_PORT || 3360');
    // the retired collection base must not survive as the fetch target
    expect(js()).not.toMatch(/API\s*=\s*'\/api\/athena'/);
  });

  it('renders a fetch failure as unreachable-API, never as an empty model', () => {
    expect(js()).toContain('FETCH_FAILED');
    expect(js()).toContain('Cannot reach the model API');
  });
});
