//! #4465 — chorus-make: a pipeline's steps and skills, as rows from the graph,
//! become the werk v2 workflow that dagu runs.
//!
//! Jeff 2026-10-09: "we design, code, test chorus-make … use chorus-make to
//! generate a new werk pipeline that is a new major version … run cards against
//! werk v1 and also against werk v2 so we have a fallback path when v2 breaks".
//!
//! One row per (PipelineStep, StepSkill, Skill), tab-separated, in this column
//! order (the SPARQL SELECT writes the same):
//!
//!   step  stepOrder  skillOrder  skill  label  executor  implementedBy  mode
//!
//! Each skill becomes one dagu step, in step order then skill order, each
//! depending on the one before. A deterministic skill runs
//! `<implementedBy> <mode>`; a human skill (Jeff's go) is a dagu `human.task`.
//! The same rows always give the same bytes.

pub const HEADER: &str =
    "# GENERATED by chorus-make from the graph (#4465). Do not edit: change the rows and regenerate.\n";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Row {
    pub step: String,
    pub step_order: u32,
    pub skill_order: u32,
    pub skill: String,
    pub label: String,
    pub executor: String,
    pub implemented_by: String,
    pub mode: String,
}

/// Rows from TSV. A line with the wrong column count or a non-number order is
/// refused by line number, never skipped.
pub fn parse_rows(tsv: &str) -> Result<Vec<Row>, Vec<String>> {
    let mut rows = Vec::new();
    let mut errs = Vec::new();
    for (i, line) in tsv.lines().enumerate() {
        let line = line.trim_end_matches('\r');
        if line.trim().is_empty() || line.starts_with('#') || line.starts_with("step\t") {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        if f.len() != 8 {
            errs.push(format!("line {}: {} columns, want 8", i + 1, f.len()));
            continue;
        }
        let (so, ko) = (f[1].trim().parse::<u32>(), f[2].trim().parse::<u32>());
        match (so, ko) {
            (Ok(step_order), Ok(skill_order)) => rows.push(Row {
                step: f[0].trim().into(),
                step_order,
                skill_order,
                skill: f[3].trim().into(),
                label: f[4].trim().into(),
                executor: f[5].trim().into(),
                implemented_by: f[6].trim().into(),
                mode: f[7].trim().into(),
            }),
            _ => errs.push(format!("line {}: stepOrder and skillOrder must be numbers", i + 1)),
        }
    }
    if errs.is_empty() { Ok(rows) } else { Err(errs) }
}

/// What the door cannot check (it does not run sh:sparql, athena-model
/// lib.rs:4453), chorus-make refuses before it writes anything.
pub fn check(rows: &[Row]) -> Vec<String> {
    let mut errs = Vec::new();
    if rows.is_empty() {
        errs.push("no rows: a pipeline with no steps is refused, never written empty".into());
    }
    let mut seen = std::collections::BTreeSet::new();
    let mut names = std::collections::BTreeSet::new();
    for r in rows {
        match r.executor.as_str() {
            "deterministic" if r.implemented_by.is_empty() => errs.push(format!(
                "{}: a deterministic skill needs implementedBy (the binary that runs it)", r.skill)),
            "deterministic" | "human" => {}
            "agent" => errs.push(format!(
                "{}: an agent skill cannot run inside the v2 workflow yet", r.skill)),
            other => errs.push(format!("{}: unknown executor '{}'", r.skill, other)),
        }
        if !names.insert(step_name(r)) {
            errs.push(format!("{}: called twice in one pipeline; dagu step names must be unique", r.skill));
        }
        if !seen.insert((r.step.clone(), r.skill_order)) {
            errs.push(format!("{}: two skills hold order {} in step {}", r.skill, r.skill_order, r.step));
        }
    }
    errs
}

/// dagu step name: the Skill row's own name (`skill-werk-deploy-werk`),
/// never one chorus-make makes up (Jeff via Silas 2026-10-09 20:34). dagu's
/// `name` takes hyphens; its `id` does not, so no id is written. The verb
/// alone is not unique (werk-deploy runs three skills).
pub fn step_name(r: &Row) -> String {
    r.skill.rsplit(['#', '/']).next().unwrap_or(&r.skill).to_string()
}

/// werk-demo's exit contract (#3237): 0 go, 2 presented and held, 1 error.
pub const PRESENTED_EXIT: u8 = 2;

/// Who may give the go (DEC-048: GO = accept). The same set chorus_werk's
/// `accepter` takes; werk-merge refuses a land without $ACCEPTER (#4474 run 9).
pub const ACCEPTERS: [&str; 4] = ["jeff", "wren", "kade", "silas"];

fn quote(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

/// The workflow text. Refuses (with every reason) rather than writing a file
/// that would run part of a pipeline.
pub fn generate(pipeline: &str, rows: &[Row]) -> Result<String, Vec<String>> {
    let errs = check(rows);
    if !errs.is_empty() {
        return Err(errs);
    }
    let mut rows = rows.to_vec();
    rows.sort_by(|a, b| (a.step_order, &a.step, a.skill_order).cmp(&(b.step_order, &b.step, b.skill_order)));
    let mut out = String::from(HEADER);
    out.push_str(&format!("description: {}\n", quote(&format!("werk v2 — pipeline {pipeline}, generated from the graph"))));
    out.push_str("params:\n  - CARD: \"\"\n  - ROLE: \"\"\n");
    // dagu hands a step only a short list of its own env (#4474 runs 1-2:
    // "CHORUS_HOME not set", then "CHORUS_WERK_BASE not set"). The machine's
    // paths pass through from the scheduler's env (launchd unit, or the shell
    // that ran `dagu start`), and dagu's run id is the trace, so every verb's
    // spine events name the run. WERK_<ROLE>_BIN are the role bin slots
    // chorus-bin-install reads (run 4); paths, not identity. No DEPLOY_ROLE: it is a self-declared
    // identity (ADR-052 retires it), and a run param must not assert one.
    out.push_str(concat!(
        "env:\n",
        "  - CHORUS_HOME: ${CHORUS_HOME}\n",
        "  - CHORUS_WERK_BASE: ${CHORUS_WERK_BASE}\n",
        "  - CHORUS_BIN: ${CHORUS_BIN}\n",
        "  - WERK_KADE_BIN: ${WERK_KADE_BIN}\n",
        "  - WERK_WREN_BIN: ${WERK_WREN_BIN}\n",
        "  - WERK_SILAS_BIN: ${WERK_SILAS_BIN}\n",
        "  - WERK_ABBY_NORMAL_BIN: ${WERK_ABBY_NORMAL_BIN}\n",
        "  - CHORUS_TRACE_ID: ${DAG_RUN_ID}\n",
    ));
    out.push_str("steps:\n");
    let mut prev: Option<String> = None;
    let mut go: Option<String> = None;
    for (i, r) in rows.iter().enumerate() {
        let before_a_human = rows.get(i + 1).is_some_and(|n| n.executor == "human");
        let id = step_name(r);
        out.push_str(&format!("  - name: {id}\n"));
        out.push_str(&format!("    description: {}\n", quote(&r.label)));
        if let Some(p) = &prev {
            out.push_str(&format!("    depends: [{p}]\n"));
        }
        if r.executor == "human" {
            // dagu 2.18 refuses a human.task with no id, and an id takes no
            // hyphens: the same row name, '-' as '_'.
            out.push_str(&format!("    id: {}\n", id.replace('-', "_")));
            out.push_str("    action: human.task\n    with:\n");
            out.push_str(&format!("      prompt: {}\n", quote(&format!("{} for #${{CARD}}?", r.label))));
            // the one who gives the go is the accepter (DEC-048): the form
            // asks who, and every later step reads it as $ACCEPTER
            out.push_str(concat!(
                "      form:\n        type: object\n        properties:\n",
                "          accepter:\n            type: string\n",
            ));
            out.push_str(&format!("            enum: [{}]\n", ACCEPTERS.join(", ")));
            out.push_str("        required: [accepter]\n");
            go = Some(id.replace('-', "_"));
        } else {
            let cmd = if r.mode.is_empty() { r.implemented_by.clone() } else { format!("{} {}", r.implemented_by, r.mode) };
            out.push_str(&format!("    command: {}\n", quote(&cmd)));
            if let Some(g) = &go {
                out.push_str(&format!("    env:\n      - ACCEPTER: ${{{g}.outputs.accepter}}\n"));
            }
            if before_a_human {
                // #4474 run 6: the verb before a human go presents and exits
                // PRESENTED_EXIT ("held for the go", werk-demo #3237); in v2 the
                // go is the next dagu step, so held is this step's success.
                // Any other non-zero exit still fails the run.
                out.push_str(&format!(
                    "    continue_on:\n      exit_code: [{PRESENTED_EXIT}]\n      mark_success: true\n"
                ));
            }
        }
        prev = Some(id);
    }
    Ok(out)
}

/// The drift check: regenerate from the rows and compare with the file on
/// disk. Any difference, a hand edit included, is a failure that names the
/// first line that differs.
pub fn drift(expected: &str, on_disk: &str) -> Result<(), String> {
    if expected == on_disk {
        return Ok(());
    }
    let (e, d): (Vec<&str>, Vec<&str>) = (expected.lines().collect(), on_disk.lines().collect());
    let n = e.iter().zip(d.iter()).position(|(a, b)| a != b).unwrap_or(e.len().min(d.len()));
    Err(format!(
        "drift at line {}: graph says {:?}, file says {:?}",
        n + 1,
        e.get(n).copied().unwrap_or("<end>"),
        d.get(n).copied().unwrap_or("<end>")
    ))
}

/// The rows chorus-make reads, one per skill a pipeline step calls. Each
/// triple sits in its own GRAPH because steps and skills live in different
/// domain graphs (pipelines, skills). `{PIPELINE}` is the pipeline's label.
pub const ROWS_QUERY: &str = r#"PREFIX chorus: <https://jeffbridwell.com/chorus#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?step ?stepOrder ?skillOrder ?skill ?label ?executor ?implementedBy ?mode WHERE {
  GRAPH ?g0 { ?pipeline a chorus:Pipeline ; rdfs:label "{PIPELINE}" ; chorus:hasStep ?s . }
  GRAPH ?g1 { ?s rdfs:label ?step ; chorus:stepOrder ?stepOrder . }
  GRAPH ?g2 { ?ss a chorus:StepSkill ; chorus:forStep ?s ; chorus:callsSkill ?skill ; chorus:skillOrder ?skillOrder . }
  GRAPH ?g3 { ?skill rdfs:label ?label ; chorus:executor ?executor .
              OPTIONAL { ?skill chorus:implementedBy ?implementedBy }
              OPTIONAL { ?skill chorus:arguments ?mode } }
}
ORDER BY ?stepOrder ?skillOrder
"#;

pub fn rows_query(pipeline: &str) -> String {
    ROWS_QUERY.replace("{PIPELINE}", &pipeline.replace(['"', '\\', '\n'], ""))
}

/// One SPARQL TSV term as plain text: <iri> → iri, "lit"^^type / "lit"@en → lit.
fn term(t: &str) -> String {
    let t = t.trim();
    if let Some(iri) = t.strip_prefix('<').and_then(|x| x.strip_suffix('>')) {
        return iri.to_string();
    }
    if let Some(rest) = t.strip_prefix('"') {
        if let Some(end) = rest.rfind('"') {
            return rest[..end].replace("\\\"", "\"").replace("\\\\", "\\").replace("\\t", " ");
        }
    }
    t.to_string()
}

/// SPARQL results (TSV, header row of ?vars) as chorus-make rows. Zero rows is
/// an error, never an empty pipeline: a wrong pipeline name, a graph that has
/// not loaded, or a shape not yet deployed all look like zero.
pub fn rows_from_sparql_tsv(tsv: &str) -> Result<Vec<Row>, Vec<String>> {
    let mut lines = tsv.lines();
    let header = lines.next().unwrap_or("");
    if !header.starts_with("?step") {
        return Err(vec![format!("not a chorus-make result: header {header:?}")]);
    }
    let body: String = lines
        .filter(|l| !l.trim().is_empty())
        .map(|l| {
            let mut f: Vec<String> = l.split('\t').map(term).collect();
            f.resize(8, String::new()); // trailing OPTIONALs may be absent
            f.join("\t") + "\n"
        })
        .collect();
    if body.is_empty() {
        return Err(vec!["the graph returned zero rows for this pipeline: refused, never an empty workflow".into()]);
    }
    parse_rows(&body)
}

// ---- ADR-062 decision 9: MCP and dagu wrap the same verb list ----

/// The werk verbs the MCP server registers as tools: every `name: 'werk-…'`.
/// chorus_werk is the pipeline trigger, not a verb, so it is not counted.
pub fn mcp_verbs(server_ts: &str) -> std::collections::BTreeSet<String> {
    server_ts
        .lines()
        .filter_map(|l| l.trim().strip_prefix("name: '"))
        .filter_map(|r| r.split('\'').next())
        .filter(|n| n.starts_with("werk-"))
        .map(str::to_string)
        .collect()
}

/// The binaries the model's deterministic skill rows run. Several skills can
/// share one binary (werk-deploy: werk, env-up, canonical); it is one verb.
pub fn skill_verbs(rows: &[Row]) -> std::collections::BTreeSet<String> {
    rows.iter()
        .filter(|r| r.executor == "deterministic" && !r.implemented_by.is_empty())
        .map(|r| r.implemented_by.clone())
        .collect()
}

/// Ok when both lists hold the same verbs. Every gap is named on its side; an
/// empty side is a read failure, never parity.
pub fn verb_parity(
    skills: &std::collections::BTreeSet<String>,
    mcp: &std::collections::BTreeSet<String>,
) -> Result<(), String> {
    if skills.is_empty() || mcp.is_empty() {
        return Err(format!("cannot compare: skills {} verbs, mcp {} verbs", skills.len(), mcp.len()));
    }
    let only_mcp: Vec<&str> = mcp.difference(skills).map(String::as_str).collect();
    let only_skills: Vec<&str> = skills.difference(mcp).map(String::as_str).collect();
    if only_mcp.is_empty() && only_skills.is_empty() {
        return Ok(());
    }
    Err(format!(
        "verb lists differ — MCP only: {} · skills only: {}",
        if only_mcp.is_empty() { "none".into() } else { only_mcp.join(", ") },
        if only_skills.is_empty() { "none".into() } else { only_skills.join(", ") },
    ))
}

// ---- #4465 AC7: one query walks the chain ----

/// value stream → its steps → the pipeline that automates it → the pipeline
/// step covering each stream step → its ordered skills → each skill's domain.
/// The second branch returns pipeline steps that cover no stream step, so a
/// missing `coversStep` is a row the check can name, not a silent gap.
pub const WALK_QUERY: &str = r##"PREFIX chorus: <https://jeffbridwell.com/chorus#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?pipeline ?vsStep ?pStep ?o ?skill ?domain WHERE {
  GRAPH ?ga { ?vs a chorus:ValueStream ; rdfs:label "{STREAM}" . }
  GRAPH ?gb { ?pipe chorus:automates ?vs ; rdfs:label ?pipeline . }
  {
    GRAPH ?gc { ?st chorus:inStream ?vs . }
    BIND(STRAFTER(STR(?st), "value-stream-step-") AS ?vsStep)
    OPTIONAL {
      GRAPH ?gd { ?pipe chorus:hasStep ?ps . ?ps chorus:coversStep ?st ; rdfs:label ?pStep . }
      OPTIONAL {
        GRAPH ?ge { ?ss chorus:forStep ?ps ; chorus:callsSkill ?sk ; chorus:skillOrder ?o . ?sk rdfs:label ?skill .
                    OPTIONAL { ?sk chorus:hasDomain ?d } }
      }
    }
  } UNION {
    GRAPH ?gf { ?pipe chorus:hasStep ?ps . ?ps rdfs:label ?pStep . FILTER NOT EXISTS { ?ps chorus:coversStep ?any } }
  }
  BIND(STRAFTER(STR(?d), "#") AS ?domain)
}
ORDER BY ?pStep ?vsStep ?o
"##;

pub fn walk_query(stream: &str) -> String {
    WALK_QUERY.replace("{STREAM}", &stream.replace(['"', '\\', '\n'], ""))
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WalkRow {
    pub stream_step: String,
    pub pipeline_step: String,
    pub order: String,
    pub skill: String,
    pub domain: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Walk {
    pub pipeline: String,
    pub rows: Vec<WalkRow>,
    /// Stream steps no pipeline step covers. Reported, not an error: a step
    /// can sit outside the pipeline on purpose (pull is /pull, before it runs).
    pub uncovered: Vec<String>,
}

pub fn walk_from_sparql_tsv(tsv: &str) -> Result<Walk, Vec<String>> {
    let mut lines = tsv.lines();
    let header = lines.next().unwrap_or("");
    if !header.starts_with("?pipeline") {
        return Err(vec![format!("not a walk result: header {header:?}")]);
    }
    let mut pipeline = String::new();
    let mut rows = Vec::new();
    for l in lines.filter(|l| !l.trim().is_empty()) {
        let mut f: Vec<String> = l.split('\t').map(term).collect();
        f.resize(6, String::new());
        pipeline = f[0].clone();
        rows.push(WalkRow { stream_step: f[1].clone(), pipeline_step: f[2].clone(), order: f[3].clone(),
                            skill: f[4].clone(), domain: f[5].clone() });
    }
    if rows.is_empty() {
        return Err(vec!["no pipeline automates this stream (or the stream is unknown): refused, never an empty walk".into()]);
    }
    let mut uncovered: Vec<String> = rows.iter().filter(|r| !r.stream_step.is_empty() && r.pipeline_step.is_empty())
        .map(|r| r.stream_step.clone()).collect();
    uncovered.dedup();
    Ok(Walk { pipeline, rows, uncovered })
}

/// Red when a pipeline step covers no stream step, a covering step calls no
/// skill, or a skill names no domain. Every gap is named.
pub fn walk_check(w: &Walk) -> Result<(), Vec<String>> {
    let mut errs: Vec<String> = Vec::new();
    for r in &w.rows {
        if r.stream_step.is_empty() {
            errs.push(format!("pipeline step `{}` covers no value-stream step", r.pipeline_step));
        } else if !r.pipeline_step.is_empty() && r.skill.is_empty() {
            errs.push(format!("pipeline step `{}` calls no skill", r.pipeline_step));
        } else if !r.skill.is_empty() && r.domain.is_empty() {
            errs.push(format!("skill `{}` names no domain", r.skill));
        }
    }
    errs.sort();
    errs.dedup();
    if errs.is_empty() { Ok(()) } else { Err(errs) }
}
