//! Demo Provenance (#1670)
//!
//! PostToolUse hook after /demo skill completes.
//! Auto-generates a demo brief to Wren's inbox so the builder
//! can't skip the paper trail.

use crate::shared::state_paths::chorus_root;
use crate::types::{HookInput, HookResponse};
use std::process::Command;
use tracing::info;

fn board_ts_path() -> String { format!("{}/platform/scripts/cards", chorus_root()) }
fn briefs_dir_path() -> String { format!("{}/platform/roles/wren/briefs", chorus_root()) }
fn chorus_log_script_path() -> String { format!("{}/platform/scripts/chorus-log", chorus_root()) }

/// PostToolUse: after /demo skill completes, generate the demo brief
pub async fn check(input: &HookInput) -> HookResponse {
    let skill = input.get_tool_input_str("skill");
    if skill != "demo" {
        return HookResponse::allow();
    }

    let args = input.get_tool_input_str("args");
    let card_id = extract_card_id(&args);
    if card_id.is_empty() {
        return HookResponse::allow();
    }

    let role = input.role();

    // Get card info
    let (title, owner) = get_card_info(&card_id);

    // Check if brief already exists (builder may have written one manually)
    let date = chrono::Utc::now().with_timezone(&super::clock_sync::boston_offset_pub()).format("%Y-%m-%d").to_string();
    let brief_path = format!("{}/{}-demo-{}.md", briefs_dir_path(), date, card_id);
    if std::path::Path::new(&brief_path).exists() {
        info!(card = %card_id, "demo-provenance: brief already exists, skipping");
        return HookResponse::allow();
    }

    // Generate brief
    let brief = format!(
        "# Demo ready: #{card_id}\n\n\
         **Builder:** {owner}\n\
         **Smoke check:** PASS\n\
         **Card:** {title}\n\
         **Demo initiated by:** {role}\n\
         **Timestamp:** {ts}\n\n\
         Auto-generated by demo-provenance hook.\n\
         Ready for Jeff + Wren review.\n",
        card_id = card_id,
        owner = if owner.is_empty() { role.as_str() } else { &owner },
        title = if title.is_empty() { "unknown" } else { &title },
        role = role.as_str(),
        ts = chrono::Utc::now().with_timezone(&super::clock_sync::boston_offset_pub()).format("%Y-%m-%dT%H:%M:%S%z"),
    );

    if std::fs::write(&brief_path, &brief).is_ok() {
        info!(card = %card_id, path = %brief_path, "demo-provenance: brief generated");

        // Emit spine event
        let log_script = chorus_log_script_path();
        let _ = Command::new(&log_script)
            .args(["card.demo.completed", role.as_str(), &format!("card={}", card_id)])
            .output();

        return HookResponse::warn_stderr(&format!(
            "Demo brief auto-generated: {}",
            brief_path.rsplit('/').next().unwrap_or(&brief_path)
        ));
    }

    HookResponse::allow()
}

fn extract_card_id(args: &str) -> String {
    args.split_whitespace()
        .find(|s| s.chars().all(|c| c.is_ascii_digit()))
        .unwrap_or("")
        .to_string()
}

fn get_card_info(card_id: &str) -> (String, String) {
    let board_script = board_ts_path();
    let output = Command::new("bash")
        .args([board_script.as_str(), "view", card_id])
        .output();

    match output {
        Ok(o) if o.status.success() => {
            let stdout = String::from_utf8_lossy(&o.stdout);
            let title = stdout.lines().next()
                .and_then(|l| l.split(&format!("#{} ", card_id)).nth(1))
                .unwrap_or("")
                .to_string();
            let owner = stdout.lines()
                .find(|l| l.contains("Owner:"))
                .and_then(|l| l.split("Owner:").nth(1))
                .map(|s| s.trim().to_lowercase())
                .unwrap_or_default();
            (title, owner)
        }
        _ => (String::new(), String::new()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::HookInput;
    use serde_json::json;

    fn make_input(tool: &str) -> HookInput {
        HookInput {
            tool_name: Some(tool.to_string()),
            tool_input: Some(json!({"command": "echo test", "file_path": "/tmp/test", "skill": "demo"})),
            tool_response: None,
            session_id: Some("test".to_string()),
            cwd: Some(format!("{}/architect", chorus_root())),
            prompt: None,
            stop_hook_active: None,
            hook_type: None,
            deploy_role: Some("silas".to_string()),
        }
    }

    #[tokio::test]
    async fn allows_non_matching_tool() {
        let input = make_input("Read");
        let r = check(&input).await;
        assert_eq!(r.exit_code, 0);
    }

    #[tokio::test]
    async fn allows_normal_input() {
        let input = make_input("Skill");
        let r = check(&input).await;
        assert_eq!(r.exit_code, 0);
    }
}
