/**
 * Brief Pipeline Flow Tests — #1240
 *
 * End-to-end validation of the brief pipeline:
 *   role writes brief → file lands in recipient's briefs/ → session hook detects → recipient reads
 *
 * Tests filesystem conventions, hook detection, and content delivery.
 */
import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

const PROJECT_ROOT = path.join(__dirname, '../../..');
const SCRIPTS_DIR = path.join(__dirname, '../../scripts');

const BRIEF_DIRS: Record<string, string> = {
  silas: path.join(PROJECT_ROOT, 'architect/briefs'),
  kade: path.join(PROJECT_ROOT, 'engineer/briefs'),
  wren: path.join(PROJECT_ROOT, 'product-manager/briefs'),
};

// ═══════════════════════════════════════════════════════════════════════════
// 1. BRIEF DIRECTORY STRUCTURE — recipient directories exist and are writable
// ═══════════════════════════════════════════════════════════════════════════

describe('Flow: Brief directory structure', () => {
  test('silas briefs directory exists', () => {
    expect(fs.existsSync(BRIEF_DIRS.silas)).toBe(true);
  });

  test('kade briefs directory exists', () => {
    expect(fs.existsSync(BRIEF_DIRS.kade)).toBe(true);
  });

  test('wren briefs directory exists', () => {
    expect(fs.existsSync(BRIEF_DIRS.wren)).toBe(true);
  });

  test('briefs are markdown files', () => {
    for (const [role, dir] of Object.entries(BRIEF_DIRS)) {
      const files = fs.readdirSync(dir).filter(f => f.endsWith('.md'));
      // Each role should have at least some briefs
      expect(files.length).toBeGreaterThan(0);
      // All should be .md
      for (const f of files) {
        expect(f).toMatch(/\.md$/);
      }
    }
  });

  test('brief filenames follow date-prefix convention', () => {
    for (const dir of Object.values(BRIEF_DIRS)) {
      const files = fs.readdirSync(dir).filter(f => f.endsWith('.md'));
      const datePattern = /^\d{4}-\d{2}-\d{2}/;
      const dated = files.filter(f => datePattern.test(f));
      // Most briefs should be date-prefixed
      expect(dated.length).toBeGreaterThan(0);
    }
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// 2. BRIEF CONTENT FORMAT — briefs have required fields
// ═══════════════════════════════════════════════════════════════════════════

describe('Flow: Brief content format', () => {
  test('board-generated briefs contain card ID and action', () => {
    // Find a card-moved brief (generated by board-ts SDK)
    for (const dir of Object.values(BRIEF_DIRS)) {
      const files = fs.readdirSync(dir).filter(f => f.includes('card-'));
      if (files.length === 0) continue;

      const content = fs.readFileSync(path.join(dir, files[0]), 'utf-8');
      expect(content).toContain('#');
      expect(content).toMatch(/Title:|Action:|Date:/);
      return;
    }
    // At least one role should have card briefs
    expect(true).toBe(true);
  });

  test('demo briefs contain required fields', () => {
    const pmDir = BRIEF_DIRS.wren;
    // Match briefs with "demo-" followed by a card number
    const demoBriefs = fs.readdirSync(pmDir)
      .filter(f => /demo-\d+/.test(f))
      .sort();
    if (demoBriefs.length === 0) {
      expect(true).toBe(true);
      return;
    }

    const content = fs.readFileSync(path.join(pmDir, demoBriefs[demoBriefs.length - 1]), 'utf-8');
    expect(content).toMatch(/Builder:|Smoke check:|Demo ready|Demo:|What shipped/i);
  });

  test('shipped briefs notify PM of completion', () => {
    const pmDir = BRIEF_DIRS.wren;
    const shippedBriefs = fs.readdirSync(pmDir).filter(f => f.includes('shipped'));
    if (shippedBriefs.length === 0) {
      expect(true).toBe(true);
      return;
    }

    const content = fs.readFileSync(path.join(pmDir, shippedBriefs[0]), 'utf-8');
    expect(content).toMatch(/shipped|Completed by|marked Done/i);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// 3. SESSION HOOK DETECTION — werk-init.sh finds new briefs
// ═══════════════════════════════════════════════════════════════════════════

describe.skip('Flow: Session hook brief [migrated to Rust] detection', () => {
  test('werk-init.sh exists and references briefs directory', () => {
    const werkInit = path.join(SCRIPTS_DIR, 'werk-init.sh');
    expect(fs.existsSync(werkInit)).toBe(true);
    const content = fs.readFileSync(werkInit, 'utf-8');
    expect(content).toContain('BRIEFS_DIR');
    expect(content).toContain('briefs');
  });

  test('werk-init.sh uses brief marker for freshness detection', () => {
    const content = fs.readFileSync(path.join(SCRIPTS_DIR, 'werk-init.sh'), 'utf-8');
    expect(content).toContain('BRIEF_MARKER');
    expect(content).toMatch(/newer/);
  });

  test('werk-init.sh emits brief.handoff.read spine event', () => {
    const content = fs.readFileSync(path.join(SCRIPTS_DIR, 'werk-init.sh'), 'utf-8');
    expect(content).toContain('brief.handoff.read');
  });

  test('werk-init.sh emits brief.handoff.acknowledged spine event', () => {
    const content = fs.readFileSync(path.join(SCRIPTS_DIR, 'werk-init.sh'), 'utf-8');
    expect(content).toContain('brief.handoff.acknowledged');
  });

  test('werk-init.sh lists up to 5 recent briefs', () => {
    const content = fs.readFileSync(path.join(SCRIPTS_DIR, 'werk-init.sh'), 'utf-8');
    expect(content).toMatch(/head -5/);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// 4. BRIEF APPEARS IN SESSION CONTEXT — session-start file includes briefs
// ═══════════════════════════════════════════════════════════════════════════

describe('Flow: Brief delivery to session context', () => {
  test('session-start file references recent briefs', () => {
    // Check any role's session-start file
    for (const role of ['silas', 'kade', 'wren']) {
      const sessionFile = `/tmp/session-start-${role}.md`;
      if (!fs.existsSync(sessionFile)) continue;

      const content = fs.readFileSync(sessionFile, 'utf-8');
      expect(content).toMatch(/Brief|brief/);
      return;
    }
    // At least one session file should exist
    expect(fs.existsSync('/tmp/session-start-silas.md')).toBe(true);
  });

  test('session-start includes brief filenames', () => {
    const sessionFile = '/tmp/session-start-silas.md';
    if (!fs.existsSync(sessionFile)) {
      expect(true).toBe(true);
      return;
    }
    const content = fs.readFileSync(sessionFile, 'utf-8');
    // Should list recent briefs with date-prefixed filenames
    expect(content).toMatch(/\d{4}-\d{2}-\d{2}.*\.md/);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// 5. STALE BRIEF DETECTION — completed workflow briefs flagged
// ═══════════════════════════════════════════════════════════════════════════

describe('Flow: Stale brief detection', () => {
  test('session-start flags stale workflow briefs', () => {
    const sessionFile = '/tmp/session-start-silas.md';
    if (!fs.existsSync(sessionFile)) {
      expect(true).toBe(true);
      return;
    }
    const content = fs.readFileSync(sessionFile, 'utf-8');
    // Stale briefs section may or may not exist depending on state
    // Just verify the concept is represented
    if (content.includes('STALE-BRIEF') || content.includes('stale brief')) {
      expect(content).toMatch(/STALE|stale/);
    } else {
      // No stale briefs — that's fine too
      expect(true).toBe(true);
    }
  });

  test('SDK notifyOwnerIfDifferent writes brief on card moves', () => {
    // Verify the SDK function creates briefs
    const sdkContent = fs.readFileSync(
      path.join(__dirname, '../src/sdk.ts'),
      'utf-8'
    );
    expect(sdkContent).toContain('notifyOwnerIfDifferent');
    expect(sdkContent).toContain('briefFile');
    expect(sdkContent).toContain('writeFileSync');
  });

  test('SDK notifyPM writes brief on card completion', () => {
    const sdkContent = fs.readFileSync(
      path.join(__dirname, '../src/sdk.ts'),
      'utf-8'
    );
    expect(sdkContent).toContain('notifyPM');
    expect(sdkContent).toContain('shipped');
  });
});
