PREFIX chorus: <https://jeffbridwell.com/chorus#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?consumer ?consumerLabel WHERE {
  GRAPH <urn:chorus:ontology> {
    ?consumer chorus:consumes <$URI> .
    OPTIONAL { ?consumer rdfs:label ?consumerLabel }
  }
} ORDER BY ?consumerLabel
