PREFIX chorus: <https://jeffbridwell.com/chorus#> PREFIX acl: <http://www.w3.org/ns/auth/acl#> SELECT ?v WHERE { GRAPH <urn:chorus:domains:security> { ?perm a chorus:Permission ; chorus:agent ?p ; chorus:accessTo ?s ; chorus:mode acl:Write . ?p a chorus:Principal ; chorus:webId ?w } BIND(CONCAT(STR(?w), " ", STR(?s)) AS ?v) }