PREFIX chorus: <https://jeffbridwell.com/chorus#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?label ?ownerLabel ?stepLabel ?comment ?consumer ?consumerLabel ?consumed ?consumedLabel ?child ?childLabel ?instance ?instanceLabel ?instanceComment ?instanceType ?instanceTypeLabel WHERE {
  GRAPH <urn:chorus:ontology> {
    <$URI> a chorus:SubDomain .
    OPTIONAL { <$URI> rdfs:label ?label }
    OPTIONAL { <$URI> chorus:ownedBy ?owner . ?owner rdfs:label ?ownerLabel }
    OPTIONAL { <$URI> chorus:primaryStep ?step . ?step rdfs:label ?stepLabel }
    OPTIONAL { <$URI> rdfs:comment ?comment }
    OPTIONAL { ?consumer chorus:consumes <$URI> . ?consumer rdfs:label ?consumerLabel }
    OPTIONAL { <$URI> chorus:consumes ?consumed . ?consumed rdfs:label ?consumedLabel }
    OPTIONAL { <$URI> chorus:hasDomain ?child . ?child rdfs:label ?childLabel }
  }
  # Contains edges + instances may live in either graph during the ADR-025 migration.
  # Until SubDomain (#2469 child #10) moves last, this needs a cross-graph view.
  OPTIONAL {
    { GRAPH <urn:chorus:ontology>  { <$URI> chorus:contains ?instance } }
    UNION
    { GRAPH <urn:chorus:instances> { <$URI> chorus:contains ?instance } }
    OPTIONAL {
      { GRAPH <urn:chorus:ontology>  { ?instance rdfs:label ?instanceLabel } }
      UNION
      { GRAPH <urn:chorus:instances> { ?instance rdfs:label ?instanceLabel } }
    }
    OPTIONAL {
      { GRAPH <urn:chorus:ontology>  { ?instance rdfs:comment ?instanceComment } }
      UNION
      { GRAPH <urn:chorus:instances> { ?instance rdfs:comment ?instanceComment } }
    }
    OPTIONAL {
      { GRAPH <urn:chorus:ontology>  { ?instance a ?instanceType } }
      UNION
      { GRAPH <urn:chorus:instances> { ?instance a ?instanceType } }
      OPTIONAL { GRAPH <urn:chorus:ontology> { ?instanceType rdfs:label ?instanceTypeLabel } }
      FILTER(?instanceType != owl:NamedIndividual)
    }
  }
}
