// GENERATED by owl-api `athena-make verb` (#3551) — DO NOT EDIT.
// Regenerated from the VerbShape; hand logic lives in athena-deploy.rs (impl AthenaDeployLogic).
// family=athena · invocability=invoked

use crate::R;

/// GENERATED seam (#3551) — implement in athena-deploy.rs. Signature projected from the
/// VerbShape; a model contract change re-projects it, so a stale impl will not compile.
pub trait AthenaDeployLogic {
    fn run(&self, dryRun: bool, ontologyGraph: String, ttl: String) -> R<String>;
}

#[derive(Debug, Clone)]
pub struct AthenaDeployInput {
    pub dryRun: bool,
    pub ontologyGraph: String,
    pub ttl: String,
}

/// wire-before-make: the verb's model placement, projected from the graph.
pub const WIRING: &[(&str, &str)] = &[
    ("atStep", "value-stream-step-deploy"),
    ("inProduct", "athena"),
];

pub fn parse_args(argv: &[String]) -> R<AthenaDeployInput> {
    Ok(AthenaDeployInput {
        dryRun: argv.get(0).ok_or_else(|| "missing arg: dryRun".to_string())?.parse::<bool>().map_err(|e| e.to_string())?,
        ontologyGraph: argv.get(1).cloned().ok_or_else(|| "missing arg: ontologyGraph".to_string())?,
        ttl: argv.get(2).cloned().ok_or_else(|| "missing arg: ttl".to_string())?,
    })
}

/// dispatch: the woven aspect scaffold (trace in / emit out) wrapping the
/// handwritten logic. owl-api owns this; the run() body lives in the seam impl.
pub fn dispatch<L: AthenaDeployLogic>(logic: &L, argv: &[String]) -> R<String> {
    let input = parse_args(argv)?;
    eprintln!("[trace] athena-deploy start");
    let out = logic.run(input.dryRun, input.ontologyGraph, input.ttl);
    eprintln!("[emit] athena-deploy done");
    out
}
