#!/usr/bin/env python3
"""Render an isolated runtime bundle; never install into a user's config.

Canonical input is designing/claudemd/{manifest.json,fragments,PROTOCOL_VERSION}.
An output directory must not exist. Review/merge/install is a separate operation.
Runtime schemas: geminicli.com/docs/hooks/reference/, opencode.ai/v2/docs/build/plugins,
opencode.ai/v2/docs/api, developers.openai.com/codex/mcp/.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import shlex
import sys
from urllib.parse import urlsplit

RUNTIMES = ("claude-code", "codex", "opencode", "gemini", "openai-compatible")
FORWARDED_ENV = ("CHORUS_ROLE", "DEPLOY_ROLE", "CHORUS_SESSION_ID",
                 "CHORUS_SESSION_TOKEN_FILE", "CHORUS_AGENT_SOCKET", "CHORUS_AGENT_STATE_DIR", "CHORUS_HOME")
MAX_FILE_BYTES = 128 * 1024
MAX_BUNDLE_BYTES = 4 * 1024 * 1024


def instructions(root, role, runtime):
    directory = root / "designing/claudemd"
    manifest = json.loads((directory / "manifest.json").read_text())
    variables = dict(manifest["variables"][role])
    variables["CHORUS_PROMPT_VERSION"] = (directory / "PROTOCOL_VERSION").read_text().strip()
    parts = []
    sources = {name: hashlib.sha256((directory / name).read_bytes()).hexdigest()
               for name in ("manifest.json", "PROTOCOL_VERSION")}
    for section in manifest["roles"][role]["sections"]:
        source = (directory / section).resolve()
        if not source.is_relative_to(directory.resolve()):
            raise ValueError("fragment escapes canonical instruction directory")
        body = source.read_text()
        sources[section] = hashlib.sha256(body.encode()).hexdigest()
        body = re.sub(r"\{\{([A-Z_]+)\}\}", lambda m: str(variables.get(m[1], m[0])), body)
        if re.search(r"\{\{[A-Z_]+\}\}", body):
            raise ValueError(f"unresolved instruction variable in {section}")
        parts.append(body.rstrip())
    note = (f"Runtime binding: {runtime}. Your Chorus role is {role}. "
            "Use the runtime's equivalent file, shell, search and delegation tools. "
            "Workflow and policy requirements above still apply. Runtime-specific "
            "tool names in historical examples are not permission grants. "
            "The launcher supplies session identity; never invent a session ID or "
            "change role identity to satisfy a denied operation.")
    return "<!-- GENERATED by agent-config.py from canonical fragments -->\n\n" + "\n\n".join(parts) + "\n\n" + note + "\n", sources


def hook_config(runtime, shim, events):
    result = {}
    for event in events:
        command = shlex.join([str(shim), "runtime-hook", runtime, event])
        # Gemini uses milliseconds; Claude Code uses seconds.
        hook = {"type": "command", "command": command,
                "timeout": 30000 if runtime == "gemini" else 30}
        group = {"hooks": [hook]}
        if event in ("PreToolUse", "PostToolUse", "PostToolUseFailure", "BeforeTool", "AfterTool"):
            group["matcher"] = ".*" if runtime == "gemini" else "*"
        result[event] = [group]
    return result


def opencode_plugin(shim):
    template = Path(__file__).with_name("agent-config-opencode.js").read_text()
    return template.replace("__CHORUS_SHIM_JSON__", json.dumps(str(shim)))


def project_skills(root, runtime):
    directory = root / "skills"
    location = {"claude-code": ".claude/skills", "codex": ".agents/skills",
                "opencode": ".opencode/skills", "gemini": ".gemini/skills",
                "openai-compatible": "skills"}[runtime]
    files, sources, records, modes = {}, {}, [], {}
    # These references need a capability-specific rewrite, not a spelling change.
    gaps = {"claude-command": r"\bclaude\s+(?:-[a-z]|attach|agents)",
            "native-delegation": r"\b(?:TaskStop|TaskOutput|subagent_type|run_in_background)\b|\b(?:Task|Agent) tool\b",
            "native-memory-path": r"(?:~/|/)[.]claude/|\bauto-memory\b",
            "native-skill-metadata": r"(?m)^(?:context|agent|allowed-tools):"}
    for entry in sorted(directory.rglob("SKILL.md")) if directory.exists() else []:
        skill_dir = entry.parent
        if not skill_dir.resolve().is_relative_to(directory.resolve()):
            raise ValueError("skill source escapes canonical skills directory")
        relative = skill_dir.relative_to(directory).as_posix()
        body = entry.read_text()
        warnings = [] if runtime == "claude-code" else [name for name, pattern in gaps.items() if re.search(pattern, body)]
        logical_tools = sorted(set(re.findall(r"mcp__chorus-api__([A-Za-z0-9_-]+)", body)))
        skill_files = []
        for source in sorted(skill_dir.rglob("*")):
            if source.is_symlink():
                raise ValueError(f"skill symlinks require explicit review: {source}")
            if not source.is_file():
                continue
            name = f"{location}/{relative}/{source.relative_to(skill_dir).as_posix()}"
            data = source.read_bytes()
            sources[source.relative_to(root).as_posix()] = hashlib.sha256(data).hexdigest()
            if source == entry and runtime != "claude-code":
                # Use logical names, never invent a host's advertised MCP prefix.
                text = re.sub(r"mcp__chorus-api__([A-Za-z0-9_-]+)", r"\1", body)
                note = (f"Runtime projection: {runtime}. MCP examples use logical tool names from server "
                        "`chorus-api`; resolve their advertised names using this runtime's tool discovery. "
                        "An unavailable tool is a capability gap; do not replace it with a bypass. "
                        "Role memory remains the canonical Chorus files. Native delegation and memory "
                        "features require verified equivalents.")
                if warnings:
                    note += " Compatibility review required: " + ", ".join(warnings) + ". The source instructions below retain these references for explicit migration."
                if text.startswith("---\n") and "\n---\n" in text[4:]:
                    end = text.index("\n---\n", 4) + 5
                    text = text[:end] + "\n> " + note + "\n\n" + text[end:]
                else:
                    text = "> " + note + "\n\n" + text
                data = text.encode()
            files[name] = data
            modes[name] = source.stat().st_mode & 0o777
            skill_files.append(name)
        records.append({"source": entry.relative_to(root).as_posix(), "id": relative,
                        "destination": f"{location}/{relative}/SKILL.md", "files": skill_files,
                        "logical_mcp_tools": logical_tools, "mcp_name_resolution": "runtime-discovery",
                        "compatibility_warnings": warnings, "conformance_verified": False})
    return files, sources, records, modes


def encoded(content):
    if isinstance(content, bytes):
        return content
    return (content if isinstance(content, str) else json.dumps(content, indent=2) + "\n").encode()


def endpoint_provider(profiles, name, runtime):
    """Render only a declared OpenCode V2 endpoint; credentials remain env refs."""
    source = profiles.read_bytes()
    document = json.loads(source)
    if document.get("version") != 1:
        raise ValueError("provider profiles require schema version 1")
    profile = document["profiles"][name]
    if runtime != "opencode" or profile.get("runtime") != "opencode":
        raise ValueError("endpoint provider rendering currently requires an OpenCode profile")
    selected = {"config": None, "profile": name, "source_sha256": hashlib.sha256(source).hexdigest(),
                "native_model": profile.get("model")}
    provider = profile.get("provider")
    if provider is None:
        return selected
    if set(provider) - {"protocol", "base_url", "api_key_env", "model_id"}:
        raise ValueError("provider allows only protocol, base_url, api_key_env and model_id references")
    protocol = provider.get("protocol")
    if protocol not in ("openai-chat", "openai-responses"):
        raise ValueError("OpenCode endpoint requires openai-chat or openai-responses")
    endpoint = provider.get("base_url", "")
    parsed = urlsplit(endpoint)
    if not parsed.hostname or parsed.username or parsed.password or parsed.query or parsed.fragment:
        raise ValueError("provider endpoint must be a URL without credentials, query or fragment")
    if parsed.scheme != "https" and not (parsed.scheme == "http" and parsed.hostname in ("localhost", "127.0.0.1", "::1")):
        raise ValueError("provider endpoint requires HTTPS except loopback")
    key = provider.get("api_key_env", "")
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key):
        raise ValueError("provider credential must name an environment variable")
    model = provider.get("model_id", "")
    if not isinstance(model, str) or not model or len(model) > 200 or any(ord(c) < 32 for c in model):
        raise ValueError("provider.model_id must name the actual endpoint model")
    if profile.get("model") not in (None, "chorus-endpoint/coder"):
        raise ValueError("profile.model must be chorus-endpoint/coder; put endpoint model in provider.model_id")
    config = {"env": [key], "package": "@opencode/ai/providers/" + ("openai-compatible/responses" if protocol == "openai-responses" else "openai-compatible"),
              "settings": {"baseURL": endpoint}, "models": {"coder": {"modelID": model}}}
    return {**selected, "config": config, "native_model": "chorus-endpoint/coder"}


def render(root, runtime, role, output, shim, node, provider=None):
    root = root.resolve()
    output = output.absolute()
    if output.exists() or output.is_symlink():
        raise ValueError("output must be a new directory; existing/custom files are never overwritten")
    if not output.parent.exists():
        raise ValueError("output parent must already exist")
    text, sources = instructions(root, role, runtime)
    entry = str(root / "platform/mcp-server/dist/main-stdio.js")
    mcp = {"command": str(node), "args": [entry]}
    files = {}
    instruction_name = {"claude-code": "CLAUDE.md", "gemini": "GEMINI.md",
                        "openai-compatible": "instructions.md"}.get(runtime, "AGENTS.md")
    files[instruction_name] = text
    capabilities = {"policy_interception": "requires-verification", "session_registration": "launcher-only"}
    if runtime == "claude-code":
        files[".mcp.json"] = {"mcpServers": {"chorus-api": {"type": "stdio", **mcp,
            "env": {name: "${" + name + "}" for name in FORWARDED_ENV}}}}
        files[".claude/settings.json"] = {"hooks": hook_config(runtime, shim,
            ["SessionStart", "PreToolUse", "PostToolUse", "PostToolUseFailure", "UserPromptSubmit", "Stop", "SessionEnd", "PreCompact"])}
    elif runtime == "gemini":
        files[".gemini/settings.json"] = {"mcpServers": {"chorus-api": {**mcp,
            "env": {name: "${" + name + "}" for name in FORWARDED_ENV}, "trust": False}},
            "hooks": hook_config(runtime, shim,
                ["SessionStart", "BeforeTool", "AfterTool", "BeforeAgent", "AfterAgent", "SessionEnd", "PreCompress"])}
    elif runtime == "opencode":
        files["opencode.json"] = {"$schema": "https://opencode.ai/config.json", "mcp": {"servers": {
            "chorus-api": {"type": "local", "command": [str(node), entry], "disabled": False,
                "environment": {name: "{env:" + name + "}" for name in FORWARDED_ENV
                                if provider is None or name != "CHORUS_SESSION_ID"}}}}}
        files[".opencode/plugins/chorus/index.js"] = opencode_plugin(shim)
        if provider is not None:
            files["opencode.json"]["mcp"]["servers"]["chorus-api"]["environment"]["CHORUS_AGENT_BINDING_PROFILE"] = provider["profile"]
            if provider["config"] is not None:
                files["opencode.json"]["providers"] = {"chorus-endpoint": provider["config"]}
            if provider["native_model"] is not None:
                files["opencode.json"]["model"] = provider["native_model"]
        capabilities["turn_stop_veto"] = "unavailable-in-observation-event"
        capabilities["mcp_identity"] = "dedicated-server-per-session-required"
        capabilities["mcp_binding"] = "operator-profile-and-role-token-file" if provider is not None else "explicit-session-id-and-role-token-file-required"
        capabilities["plugin_api"] = "opencode-v2-requires-conformance-verification"
    elif runtime == "codex":
        files[".codex/config.toml"] = ("# GENERATED by agent-config.py; merge only after review.\n"
            "[mcp_servers.chorus-api]\ncommand = " + json.dumps(str(node)) + "\nargs = " + json.dumps([entry]) +
            "\nenv_vars = " + json.dumps(FORWARDED_ENV) + "\n")
        files[".codex/hooks.json"] = {"hooks": hook_config(runtime, shim,
            ["SessionStart", "PreToolUse", "PostToolUse", "UserPromptSubmit", "Stop", "SessionEnd"])}
        capabilities["policy_interception"] = "requires-verification-and-project-hook-trust"
    else:
        files["mcp.json"] = {"mcpServers": {"chorus-api": {"type": "stdio", **mcp}}}
        capabilities["policy_interception"] = "supervisor-owned-tool-execution-required"
    skill_files, skill_sources, skills, modes = project_skills(root, runtime)
    files.update(skill_files)
    sources.update(skill_sources)
    generated = {name: {"bytes": len(encoded(content)), "sha256": hashlib.sha256(encoded(content)).hexdigest()}
                 for name, content in files.items()}
    total = sum(info["bytes"] for info in generated.values())
    oversized = [name for name, info in generated.items() if info["bytes"] > MAX_FILE_BYTES]
    if oversized or total > MAX_BUNDLE_BYTES:
        raise ValueError(f"generated bundle exceeds byte budget: files={oversized}, total={total}")
    files["bundle.json"] = {"version": 1, "runtime": runtime, "role": role,
        "instruction_file": instruction_name, "capabilities": capabilities,
        "source_hashes": sources, "files": sorted(files), "generated_files": generated,
        "skills": skills, "budget": {"max_file_bytes": MAX_FILE_BYTES, "max_total_bytes": MAX_BUNDLE_BYTES,
        "content_bytes": total}, "installed": False}
    if provider is not None:
        files["bundle.json"]["provider_source"] = {"profile": provider["profile"], "sha256": provider["source_sha256"],
                                                   "native_model": provider["native_model"]}
    manifest_bytes = len(encoded(files["bundle.json"]))
    if manifest_bytes > MAX_FILE_BYTES or total + manifest_bytes > MAX_BUNDLE_BYTES:
        raise ValueError("generated bundle manifest exceeds byte budget")
    # Validation precedes directory creation. Exclusive mkdir prevents collisions.
    output.mkdir(mode=0o700)
    for name, content in files.items():
        destination = output / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        with destination.open("xb") as handle:
            handle.write(encoded(content))
        if name in modes:
            destination.chmod(modes[name] & 0o755)
    return output


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--runtime", choices=RUNTIMES, required=True)
    parser.add_argument("--role", choices=("wren", "silas", "kade"), required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--shim", type=Path, default=Path.home() / ".chorus/bin/chorus-hook-shim")
    parser.add_argument("--node", default="node")
    parser.add_argument("--profiles", type=Path, help="Optional operator profile JSON for OpenCode endpoint configuration")
    parser.add_argument("--profile", help="Profile whose provider.model_id is rendered as chorus-endpoint/coder")
    args = parser.parse_args()
    try:
        if bool(args.profiles) != bool(args.profile):
            raise ValueError("--profiles and --profile must be supplied together")
        provider = endpoint_provider(args.profiles, args.profile, args.runtime) if args.profiles else None
        output = render(args.root, args.runtime, args.role, args.output, args.shim, args.node, provider)
        print(json.dumps({"ok": True, "output": str(output), "installed": False}))
    except (ValueError, KeyError, OSError) as error:
        print(f"agent-config: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
