#!/usr/bin/env bash
# generate-standards-surface.sh — Produce live HTML from decisions, hooks, and gate logs
# Card #2266: Replace hardcoded counts with real data from three sources
#
# Data sources:
#   1. decisions.md — count of DEC-NNN entries
#   2. chorus-hooks/src/hooks/*.rs — count of Rust hook modules
#   3. ~/Library/Logs/Gathering/hooks.log — gate enforcement rates (trailing 7 days)
#
# Pattern: claudemd-gen (read sources, template output, idempotent)
set -euo pipefail

# --- Configuration ---
REPO_ROOT="/Users/jeffbridwell/CascadeProjects/chorus"
DECISIONS_MD="$REPO_ROOT/product-manager/decisions.md"
HOOKS_DIR="$REPO_ROOT/platform/services/chorus-hooks/src/hooks"
PULSE_LOG="$HOME/Library/Logs/Gathering/hooks.log"
MEMORY_DIR="$HOME/.claude/projects/-Users-jeffbridwell-CascadeProjects/memory"
APP_DOCS="/Users/jeffbridwell/CascadeProjects/jeff-bridwell-personal-site/public/gathering-docs"

# Allow override for testing
OUTPUT_DIR="${APP_DOCS}"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-dir) OUTPUT_DIR="$2"; shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

mkdir -p "$OUTPUT_DIR"

# --- Harvest data ---

# 1. Decision count
DECISION_COUNT=$(grep -c "^## DEC-" "$DECISIONS_MD" 2>/dev/null || echo 0)

# 2. Hook module count (exclude mod.rs)
HOOK_COUNT=$(ls "$HOOKS_DIR"/*.rs 2>/dev/null | grep -v mod.rs | wc -l | tr -d ' ')

# 3. Feedback and story counts from memory files
FEEDBACK_COUNT=$(ls "$MEMORY_DIR"/feedback_*.md 2>/dev/null | wc -l | tr -d ' ')
STORY_COUNT=$(ls "$MEMORY_DIR"/story_*.md 2>/dev/null | wc -l | tr -d ' ')

# 4. Gate enforcement rates from pulse log (trailing 7 days)
SEVEN_DAYS_AGO=$(date -v-7d '+%Y-%m-%d')

# Parse enriched pulse log format:
# timestamp | hook_type | tool | role | module | decision | duration | session_id | context
# Decisions: allow, block, deny (skip 'enter' — that's pre-check)
if [ -f "$PULSE_LOG" ]; then
  # Get trailing 7 days of entries
  RECENT_LOG=$(awk -v cutoff="$SEVEN_DAYS_AGO" '$1 >= cutoff' "$PULSE_LOG")

  # Count decisions by type
  ALLOW_COUNT=$(echo "$RECENT_LOG" | awk -F' \\| ' '{gsub(/^ +| +$/, "", $6)} tolower($6) == "allow"' | wc -l | tr -d ' ')
  BLOCK_COUNT=$(echo "$RECENT_LOG" | awk -F' \\| ' '{gsub(/^ +| +$/, "", $6)} tolower($6) == "block"' | wc -l | tr -d ' ')
  DENY_COUNT=$(echo "$RECENT_LOG" | awk -F' \\| ' '{gsub(/^ +| +$/, "", $6)} tolower($6) == "deny"' | wc -l | tr -d ' ')

  TOTAL_DECISIONS=$(( ALLOW_COUNT + BLOCK_COUNT + DENY_COUNT ))

  # Modules with at least one block or deny = gate-enforced
  ENFORCED_MODULES=$(echo "$RECENT_LOG" | awk -F' \\| ' '{gsub(/^ +| +$/, "", $5); gsub(/^ +| +$/, "", $6)} tolower($6) == "block" || tolower($6) == "deny" {print $5}' | sort -u | wc -l | tr -d ' ')

  # Modules with only allow = partial (they run but never block)
  ALL_ACTIVE_MODULES=$(echo "$RECENT_LOG" | awk -F' \\| ' '{gsub(/^ +| +$/, "", $5); gsub(/^ +| +$/, "", $6)} tolower($6) == "allow" || tolower($6) == "block" || tolower($6) == "deny" {print $5}' | sort -u | wc -l | tr -d ' ')
  PARTIAL_MODULES=$(( ALL_ACTIVE_MODULES - ENFORCED_MODULES ))

  # Doc-only = total hook modules minus active modules
  DOC_ONLY_MODULES=$(( HOOK_COUNT - ALL_ACTIVE_MODULES ))
  [ "$DOC_ONLY_MODULES" -lt 0 ] && DOC_ONLY_MODULES=0

  # Percentages
  if [ "$HOOK_COUNT" -gt 0 ]; then
    PCT_ENFORCED=$(( ENFORCED_MODULES * 100 / HOOK_COUNT ))
    PCT_PARTIAL=$(( PARTIAL_MODULES * 100 / HOOK_COUNT ))
    PCT_DOC=$(( 100 - PCT_ENFORCED - PCT_PARTIAL ))
  else
    PCT_ENFORCED=0; PCT_PARTIAL=0; PCT_DOC=100
  fi
else
  ALLOW_COUNT=0; BLOCK_COUNT=0; DENY_COUNT=0; TOTAL_DECISIONS=0
  ENFORCED_MODULES=0; PARTIAL_MODULES=0; DOC_ONLY_MODULES="$HOOK_COUNT"
  PCT_ENFORCED=0; PCT_PARTIAL=0; PCT_DOC=100
fi

GENERATED_DATE=$(TZ=America/New_York date '+%Y-%m-%d %H:%M')

# --- Generate chorus-standards.html ---
# Strategy: read the existing curated HTML, replace the data-driven sections
# (header counts and instrumentation bar), preserve everything else.

EXISTING_STANDARDS="$APP_DOCS/chorus-standards.html"
if [ -f "$EXISTING_STANDARDS" ]; then
  # Read the existing file and replace the dynamic sections
  python3 - "$EXISTING_STANDARDS" "$OUTPUT_DIR/chorus-standards.html" \
    "$DECISION_COUNT" "$FEEDBACK_COUNT" "$STORY_COUNT" \
    "$PCT_ENFORCED" "$PCT_PARTIAL" "$PCT_DOC" \
    "$GENERATED_DATE" <<'PYEOF'
import sys, re

src, dst = sys.argv[1], sys.argv[2]
dec, fb, st = sys.argv[3], sys.argv[4], sys.argv[5]
pct_e, pct_p, pct_d = sys.argv[6], sys.argv[7], sys.argv[8]
gen_date = sys.argv[9]

with open(src) as f:
    html = f.read()

# Replace date line — match the existing pattern
html = re.sub(
    r'(<div class="date">).*?(</div>)',
    rf'\g<1>{gen_date} — Generated by generate-standards-surface.sh. '
    rf'Sources: {dec} decisions, {fb} feedback memories, {st} stories.\g<2>',
    html, count=1
)

# Replace summary card numbers
cards = re.findall(r'<div class="summary-card">.*?</div></div>', html, re.DOTALL)
replacements = [
    (r'<div class="number">\d+</div>(<div class="label">Decisions</div>)',
     rf'<div class="number">{dec}</div>\1'),
    (r'<div class="number">\d+</div>(<div class="label">Feedback Rules</div>)',
     rf'<div class="number">{fb}</div>\1'),
    (r'<div class="number">\d+</div>(<div class="label">Stories</div>)',
     rf'<div class="number">{st}</div>\1'),
]
for pattern, repl in replacements:
    html = re.sub(pattern, repl, html, count=1)

# Replace instrumentation bar widths
html = re.sub(r'(bar-instrumented" style="width: )\d+%', rf'\g<1>{pct_e}%', html)
html = re.sub(r'(bar-partial" style="width: )\d+%', rf'\g<1>{pct_p}%', html)
html = re.sub(r'(bar-documented" style="width: )\d+%', rf'\g<1>{pct_d}%', html)

# Replace legend percentages
html = re.sub(r'Gate-enforced \(\d+%\)', f'Gate-enforced ({pct_e}%)', html)
html = re.sub(r'Partially instrumented \(\d+%\)', f'Partially instrumented ({pct_p}%)', html)
html = re.sub(r'Documented only \(\d+%\)', f'Documented only ({pct_d}%)', html)

with open(dst, 'w') as f:
    f.write(html)
PYEOF
else
  echo "Warning: $EXISTING_STANDARDS not found, skipping standards HTML" >&2
fi

# --- Generate chorus-hook-architecture.html ---
# Replace the header counts and gap status with live data

EXISTING_HOOKS="$APP_DOCS/chorus-hook-architecture.html"
if [ -f "$EXISTING_HOOKS" ]; then
  python3 - "$EXISTING_HOOKS" "$OUTPUT_DIR/chorus-hook-architecture.html" \
    "$HOOK_COUNT" "$GENERATED_DATE" \
    "$ENFORCED_MODULES" "$BLOCK_COUNT" "$DENY_COUNT" <<'PYEOF'
import sys, re

src, dst = sys.argv[1], sys.argv[2]
hook_count = sys.argv[3]
gen_date = sys.argv[4]
enforced = sys.argv[5]
blocks = sys.argv[6]
denies = sys.argv[7]

with open(src) as f:
    html = f.read()

# Update hook count in intro paragraph
html = re.sub(r'\d+ hook modules', f'{hook_count} hook modules', html, count=1)

# Update generation date
html = re.sub(
    r'generated \d{4}-\d{2}-\d{2}',
    f'generated {gen_date[:10]}',
    html, count=1
)

# Update the update date
html = re.sub(
    r'updated \d{4}-\d{2}-\d{2}[^<]*',
    f'updated {gen_date[:10]} by generate-standards-surface.sh. '
    f'{enforced} modules actively enforcing ({blocks} blocks, {denies} denies trailing 7d).',
    html, count=1
)

with open(dst, 'w') as f:
    f.write(html)
PYEOF
else
  echo "Warning: $EXISTING_HOOKS not found, skipping hooks HTML" >&2
fi

# Summary to stderr (stdout is data)
echo "Generated: $OUTPUT_DIR" >&2
echo "  Decisions: $DECISION_COUNT | Feedback: $FEEDBACK_COUNT | Stories: $STORY_COUNT" >&2
echo "  Hook modules: $HOOK_COUNT | Enforced: $ENFORCED_MODULES | Partial: $PARTIAL_MODULES | Doc-only: $DOC_ONLY_MODULES" >&2
echo "  Instrumentation: ${PCT_ENFORCED}% gate / ${PCT_PARTIAL}% partial / ${PCT_DOC}% doc" >&2
echo "  Pulse log (7d): $ALLOW_COUNT allow, $BLOCK_COUNT block, $DENY_COUNT deny" >&2
