#!/usr/bin/env bash
# harvest-alerts.sh — #4085
#
# Turn the alert rules that already exist on disk into chorus:Alert rows.
#
# Two sources, because those are the two ways this system interrupts a person:
#
#   grafana  provisioned rules in shared-observability/.../alerting/*.yaml
#   script   shell scripts that call platform/scripts/ops-nudge
#
# Counted 2026-09-06: 7 grafana, 13 script. The 13 are most of what actually
# reaches Jeff, so a harvester that read only Grafana would report a third of
# the surface and look complete doing it.
#
# DECLARED, NEVER GUESSED. Every alert says which domain it watches, in its own
# file:
#
#   grafana rule   labels:  domain: infrastructure
#   script         # alert-domain: infrastructure   (anywhere in the file)
#
# An alert with no declaration is NOT given a default and NOT dropped. The run
# fails, names the file, and writes nothing. Guessing a domain from a filename
# would fill the fold with plausible wrong answers, which is worse than empty —
# a reader cannot tell a guess from a fact once it is a row.
#
# Output is Turtle on stdout. Writing to the graph is the caller's job
# (chorus-model / the domain API), so this script is safe to run and read.

set -euo pipefail

ROOT="${CHORUS_ROOT:-$HOME/CascadeProjects/chorus}"
OBS="${SHARED_OBS_ROOT:-$HOME/CascadeProjects/shared-observability}"
ALERT_YAML_DIR="$OBS/config/grafana/provisioning/alerting"
SCRIPTS_DIR="$ROOT/platform/scripts"

undeclared_n=0
undeclared_f="$(mktemp)"
trap 'rm -f "$undeclared_f"' EXIT
emitted=0

emit_header() {
  cat <<'TTL'
@prefix chorus: <https://jeffbridwell.com/chorus#> .
@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .

# Generated by harvest-alerts.sh (#4085). Do not hand-edit — rerun the harvester.
TTL
  echo "# Harvested: $(TZ=America/New_York date '+%Y-%m-%d %H:%M %Z')"
  echo ""
}

# slugify <text> — a stable local name from a human title.
slugify() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E -e 's/[^a-z0-9]+/-/g' -e 's/^-//' -e 's/-$//'
}

emit_row() {
  local slug="$1" label="$2" source="$3" file="$4" domain="$5" route="$6"
  printf 'chorus:alert-%s a chorus:Alert ;\n' "$slug"
  printf '    rdfs:label "%s" ;\n' "${label//\"/\\\"}"
  printf '    chorus:alertSource "%s" ;\n' "$source"
  printf '    chorus:alertFile "%s" ;\n' "$file"
  [ -n "$route" ] && printf '    chorus:alertRoute "%s" ;\n' "$route"
  printf '    chorus:hasDomain chorus:%s .\n\n' "$domain"
  emitted=$((emitted + 1))
}

# --- grafana provisioned rules ------------------------------------------------
# Each rule is a `- title:` under a group; its domain is a `domain:` entry in
# that rule's own labels block. Parsed in one pass so a rule and its label can
# never be paired across a boundary.
harvest_grafana() {
  local f
  for f in "$ALERT_YAML_DIR"/*.yaml "$ALERT_YAML_DIR"/*.yml; do
    [ -f "$f" ] || continue
    local rel="${f#"$HOME/CascadeProjects/"}"
    python3 - "$f" "$rel" <<'PY'
import re, sys
path, rel = sys.argv[1], sys.argv[2]
lines = open(path).read().splitlines()
rules = []          # (title, domain|None, receiver|None)
cur = None
for ln in lines:
    m = re.match(r'\s*(?:-\s+)?title:\s*(.+?)\s*$', ln)
    if m and 'annotations' not in ln:
        if cur: rules.append(cur)
        cur = [m.group(1).strip().strip('"'), None, None]
        continue
    if cur:
        d = re.match(r'\s*domain:\s*([A-Za-z0-9_-]+)\s*(?:#.*)?$', ln)
        if d: cur[1] = d.group(1)
        r = re.match(r'\s*receiver:\s*(.+?)\s*$', ln)
        if r: cur[2] = r.group(1).strip().strip('"')
if cur: rules.append(cur)
for title, domain, receiver in rules:
    print("\x1f".join([title, domain or "", receiver or "", rel]))
PY
  done
}

# --- scripts that fire through ops-nudge --------------------------------------
harvest_scripts() {
  local f
  while IFS= read -r f; do
    [ -f "$f" ] || continue
    # ops-nudge itself is the delivery path, not an alert.
    # ops-nudge is the delivery path, not an alert; this script only names it.
    case "$(basename "$f")" in ops-nudge|harvest-alerts.sh) continue ;; esac
    local name rel domain route
    name="$(basename "$f")"
    rel="chorus/platform/scripts/$name"
    domain="$(grep -m1 -oE '^#[[:space:]]*alert-domain:[[:space:]]*[A-Za-z0-9_-]+' "$f" 2>/dev/null \
              | sed -E 's/.*alert-domain:[[:space:]]*//')" || true
    # the role ops-nudge is called with, when it is a literal
    route="$(grep -m1 -oE 'ops-nudge"?[[:space:]]+(silas|wren|kade)' "$f" 2>/dev/null \
             | grep -oE '(silas|wren|kade)$')" || true
    printf '%s\x1f%s\x1f%s\x1f%s\n' "$name" "$domain" "$route" "$rel"
  done < <(grep -rl "ops-nudge" "$SCRIPTS_DIR" 2>/dev/null | sort)
}

main() {
  local out
  out="$(mktemp)"

  emit_header >> "$out"

  echo "# --- grafana provisioned rules ---" >> "$out"
  while IFS=$'\x1f' read -r title domain receiver rel; do
    [ -n "$title" ] || continue
    if [ -z "$domain" ]; then
      echo "  grafana: \"$title\" in $rel" >> "$undeclared_f"; undeclared_n=$((undeclared_n+1))
      continue
    fi
    emit_row "$(slugify "$title")" "$title" "grafana" "$rel" "$domain" "$receiver" >> "$out"
  done < <(harvest_grafana)

  echo "# --- scripts firing through ops-nudge ---" >> "$out"
  while IFS=$'\x1f' read -r name domain route rel; do
    [ -n "$name" ] || continue
    if [ -z "$domain" ]; then
      echo "  script: $rel" >> "$undeclared_f"; undeclared_n=$((undeclared_n+1))
      continue
    fi
    emit_row "$(slugify "${name%.sh}")" "$name" "script" "$rel" "$domain" "$route" >> "$out"
  done < <(harvest_scripts)

  if [ "$undeclared_n" -gt 0 ]; then
    {
      echo "harvest-alerts: REFUSING — $undeclared_n alert(s) do not declare a domain."
      echo "Nothing was written. Each alert must say what it watches, in its own file:"
      echo "  grafana rule:  add   domain: <name>   to that rule's labels block"
      echo "  script:        add   # alert-domain: <name>"
      cat "$undeclared_f"
    } >&2
    exit 1
  fi

  cat "$out"
  echo "harvest-alerts: $emitted Alert rows" >&2
}

main "$@"
