#!/usr/bin/env python3
"""#4175 — generate the per-product appointment rows from ownedBy.

Jeff's rule, 2026-09-14: "the owner wears all 4 for their products domains and
services." So an appointment is DERIVED, never authored by hand — every anchor
that has an owner gets exactly four rows, one per per-product hat, appointee =
that owner. Hand-typing 264 rows would be four chances per anchor to disagree
with ownedBy; a generator has none.

Reads the store (the anchors and their owners are harvested data, not ours to
restate) and writes roles/wren/ontology/hats-appointments-4175.ttl. An anchor
with NO owner is reported and skipped — not guessed at.

Usage: hats-appointments-4175.py [--out FILE] [--query URL]
"""
import argparse, collections, sys, urllib.parse, urllib.request

NS = "https://jeffbridwell.com/chorus#"
HATS = ["hat-product-manager", "hat-solutions-architect",
        "hat-engineering-lead", "hat-operations-lead"]
# The owner is NOT always in the same graph as the type — one domain's ownedBy
# lives elsewhere, and an OPTIONAL nested inside GRAPH ?g silently reported it
# as unowned. ?h is a separate graph variable for exactly that reason.
Q = """PREFIX c: <%s>
SELECT ?anchor ?kind ?owner WHERE {
  GRAPH ?g { ?anchor a ?kind . FILTER(?kind IN (c:Product, c:Domain, c:Service)) }
  OPTIONAL { GRAPH ?h { ?anchor c:ownedBy ?owner } }
} ORDER BY ?kind ?anchor""" % NS


def rows(endpoint):
    req = urllib.request.Request(
        endpoint, data=urllib.parse.urlencode({"query": Q}).encode(),
        headers={"Accept": "text/csv"})
    body = urllib.request.urlopen(req, timeout=30).read().decode()
    out = []
    for line in body.splitlines()[1:]:
        if not line.strip():
            continue
        parts = line.split(",")
        out.append((parts[0], parts[1], parts[2] if len(parts) > 2 else ""))
    return out


def local(iri):
    return iri.rsplit("#", 1)[-1] if iri else ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--query", default="http://localhost:3030/pods/query")
    ap.add_argument("--out", default="roles/wren/ontology/hats-appointments-4175.ttl")
    a = ap.parse_args()

    # An anchor can be typed in more than one graph, and only one of those rows
    # may carry the owner. Collect first, decide after — deciding row-by-row
    # reported a domain as unowned because its owner-less duplicate came last.
    kinds, owners = {}, {}
    for anchor, kind, owner in rows(a.query):
        kinds[anchor] = local(kind)
        if owner:
            owners[anchor] = local(owner)
    seen = {k: (kinds[k], owners[k]) for k in owners}
    unowned = [k for k in kinds if k not in owners]

    by_kind = collections.Counter(k for k, _ in seen.values())
    # A subject typed as more than one anchor kind is counted once, under
    # whichever type sorted last — it is still one anchor with one owner and
    # four hats. chorus:spine is typed both Product and Domain today (#4044,
    # "'spine' means two different things in the catalog"), which is why the
    # Domain tally below reads 41 against 42 Domain rows in the store.
    lines = [
        "@prefix chorus: <%s> ." % NS,
        "@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .",
        "",
        "# GENERATED by platform/scripts/hats-appointments-4175.py — do not hand-edit.",
        "#",
        "# Jeff's rule, 2026-09-14: \"the owner wears all 4 for their products domains",
        "# and services.\" Four appointments per owned anchor, appointee = ownedBy, so",
        "# an appointment can never disagree with the ownership it qualifies — which is",
        "# what gc-appointee-is-the-owner refuses. Re-run after any ownership change.",
        "#",
        "# %d owned anchors (%s) x 4 hats = %d appointments." % (
            len(seen), ", ".join("%d %s" % (n, k) for k, n in sorted(by_kind.items())),
            len(seen) * 4),
    ]
    if unowned:
        lines += ["#", "# NOT APPOINTED — no chorus:ownedBy, reported rather than guessed at:"]
        lines += ["#   %s" % local(u) for u in sorted(unowned)]
    lines.append("")

    for anchor in sorted(seen):
        kind, owner = seen[anchor]
        for hat in HATS:
            name = "appt-%s-%s" % (local(anchor), hat[4:])
            lines += [
                "chorus:%s a chorus:Appointment ;" % name,
                '    rdfs:label "%s over %s" ;' % (hat[4:].replace("-", " "), local(anchor)),
                '    chorus:label "%s over %s" ;' % (hat[4:].replace("-", " "), local(anchor)),
                "    chorus:appointee chorus:%s ;" % owner,
                "    chorus:appointedHat chorus:%s ;" % hat,
                "    chorus:overAnchor chorus:%s ." % local(anchor),
                "",
            ]
    open(a.out, "w").write("\n".join(lines))
    print("wrote %s — %d appointments over %d anchors; %d unowned anchor(s) skipped"
          % (a.out, len(seen) * 4, len(seen), len(unowned)), file=sys.stderr)


if __name__ == "__main__":
    main()
