#!/usr/bin/env bash
# render-share-principals.sh — the guard's WHO, projected from the model. (#3776, ADR-057)
#
# The model is the policy: a Principal with canSignIn "true" is admitted at the
# public door; everyone else is not. This renders that projection from the SAME
# source file the deploy validates (identity-principals-3613.ttl), so the list
# the guard enforces is provably the list the model declares. Hand-editing the
# output is a defect — fitness row 8 re-renders and diffs on every run.
#
# Fail-closed twice over: riot must parse the source, and the projection must be
# non-empty — an empty allow-set is never written, because the guard treats an
# empty file as refuse-to-start and a rendered-empty file would smuggle that
# state past a reviewer as "generated, must be right".
set -euo pipefail

CHORUS_ROOT="${CHORUS_ROOT:-/Users/jeffbridwell/CascadeProjects/chorus}"
SRC="${1:-$CHORUS_ROOT/roles/silas/ontology/identity-principals-3613.ttl}"
OUT="${2:-$CHORUS_ROOT/config/share-principals.txt}"
NS="https://jeffbridwell.com/chorus#"

command -v riot >/dev/null 2>&1 || { echo "render-share-principals: riot not found — cannot parse the model, refusing to guess" >&2; exit 2; }
NT=$(riot --output=ntriples "$SRC") || { echo "render-share-principals: $SRC does not parse — not rendering" >&2; exit 2; }

WEBIDS=$(printf '%s\n' "$NT" | awk -v ns="$NS" '
  $2 == "<" ns "canSignIn>" && $3 ~ /^"true"/ { yes[$1] = 1 }
  $2 == "<" ns "webId>" {
    v = $0
    sub(/^[^"]*"/, "", v); sub(/".*$/, "", v)
    webid[$1] = v
  }
  END { for (s in yes) if (s in webid) print webid[s] }
' | sort)

[ -n "$WEBIDS" ] || { echo "render-share-principals: projection is EMPTY — refusing to write an allow-set that admits no one" >&2; exit 2; }

TMP=$(mktemp)
{
  echo "# GENERATED by render-share-principals.sh from $(basename "$SRC") — DO NOT HAND-EDIT (#3776, ADR-057)"
  echo "#"
  echo "# This file is a PROJECTION: the guard's allow-set is the set of Principals"
  echo "# the model declares with canSignIn \"true\". To add or remove a person, edit"
  echo "# the model and re-render; a hand edit here diverges from the model and"
  echo "# fitness row 8 goes red on it. Authentication stays the identity provider's"
  echo "# job; this file is WHO MAY ENTER once authenticated, consulted per request."
  printf '%s\n' "$WEBIDS"
} > "$TMP"
chmod 644 "$TMP"
mv "$TMP" "$OUT"
echo "render-share-principals: $(printf '%s\n' "$WEBIDS" | wc -l | tr -d ' ') webid(s) -> $OUT" >&2
