#!/usr/bin/env bash
# #3870 — service harvester, generate phase: launchctl snapshot JSON →
# ServiceInstance/ScheduledJob TTL. Pure transform: same snapshot + timestamp
# in, byte-identical TTL out (the loader diffs before posting, so run-twice
# writes nothing — a harvest, not an append). Vanish handling: units present
# in --previous but missing from the snapshot survive with runState "absent"
# (the drift check's job is to name them; deleting them would blind it).
# Exit 2 on missing inputs — an empty harvest must never impersonate a quiet one.
set -euo pipefail

SNAPSHOT="" TIMESTAMP="" OUT="" PREVIOUS="" MAPPING="" SERVICES_TTL=""
while [ $# -gt 0 ]; do
  case "$1" in
    --snapshot)     SNAPSHOT="$2"; shift 2 ;;
    --timestamp)    TIMESTAMP="$2"; shift 2 ;;
    --out)          OUT="$2"; shift 2 ;;
    --previous)     PREVIOUS="$2"; shift 2 ;;
    --mapping)      MAPPING="$2"; shift 2 ;;
    --services-ttl) SERVICES_TTL="$2"; shift 2 ;;
    *) echo "service-harvest-gen: unknown arg $1" >&2; exit 2 ;;
  esac
done
[ -z "$MAPPING" ] || [ -f "$MAPPING" ] || { echo "service-harvest-gen: mapping file not found" >&2; exit 2; }
[ -z "$MAPPING" ] || [ -n "$SERVICES_TTL" ] || { echo "service-harvest-gen: --mapping requires --services-ttl (edges must validate against authored Services)" >&2; exit 2; }
[ -z "$SERVICES_TTL" ] || [ -f "$SERVICES_TTL" ] || { echo "service-harvest-gen: services TTL not found" >&2; exit 2; }
[ -n "$SNAPSHOT" ] && [ -f "$SNAPSHOT" ] || { echo "service-harvest-gen: snapshot missing" >&2; exit 2; }
[ -n "$TIMESTAMP" ] || { echo "service-harvest-gen: --timestamp required (determinism: the caller owns the clock)" >&2; exit 2; }
[ -n "$OUT" ] || { echo "service-harvest-gen: --out required" >&2; exit 2; }
[ -z "$PREVIOUS" ] || [ -f "$PREVIOUS" ] || { echo "service-harvest-gen: previous TTL not found" >&2; exit 2; }

python3 - "$SNAPSHOT" "$TIMESTAMP" "$OUT" "${PREVIOUS:-}" "${MAPPING:-}" "${SERVICES_TTL:-}" <<'PYEOF'
import json, sys, re

snapshot_path, ts, out_path, prev_path, map_path, services_path = sys.argv[1:7]
snap = json.load(open(snapshot_path))

# Authored label→Service mapping (wren-ack 16:23, two conditions enforced):
# unknown Service IRI = REFUSE here (condition 2); mapped label with no
# observed instance = machine-written staleness row the drift check names
# (condition 1). The mapping stays authored; every graph row stays generated.
mapping = json.load(open(map_path)) if map_path else {}
mapping = {k: v for k, v in mapping.items() if not k.startswith("_")}  # _comment etc.
if mapping:
    services_ttl = open(services_path).read()
    valid = set(re.findall(r"chorus:(service-[A-Za-z0-9-]+)\s+a\s+chorus:Service", services_ttl))
    bad = sorted(set(mapping.values()) - valid)
    if bad:
        print(f"service-harvest-gen: REFUSE — mapping targets unknown Service(s): {', '.join(bad)}", file=sys.stderr)
        sys.exit(2)

def esc(s): return s.replace('\\', '\\\\').replace('"', '\\"')

OURS = ("/Users/jeffbridwell/CascadeProjects/", "/Users/jeffbridwell/.chorus/")
def evidence_paths(rec):
    # Full argv beats argv0: com.security.css runs as /bin/bash + our
    # start.sh — argv0 alone would mark OUR unit external (caught live
    # 2026-08-14). A bundle id (SMAppService apps) is external evidence too.
    paths = list(rec.get("argv") or [])
    if rec.get("program"):
        paths.append(rec["program"])
    return paths

OUR_LABELS = ("com.gathering.", "com.chorus.", "com.security.")
def is_ours(rec, label=""):
    # Two evidence kinds: a path in our trees, OR a label in a namespace WE
    # minted (com.gathering.ollama wraps /Applications/Ollama.app — the label
    # is ours even when the binary is an app; caught live 2026-08-14).
    # Discovery stays unrestricted — this classifies ownership, it never
    # filters what the walk sees.
    if label.startswith(OUR_LABELS):
        return True
    return any(p.startswith(OURS) for p in evidence_paths(rec))

def is_external(rec, label=""):
    # Evidence-derived, never hand-typed (wren). Ours-wins: our label
    # namespace or any argument in our trees → ours. Else: any path/bundle
    # evidence → external. NO evidence → unknowable, stays in the unmapped
    # pool where scrutiny lives (docker.helper class).
    if is_ours(rec, label):
        return False
    return bool(evidence_paths(rec)) or bool(rec.get("bundleId"))

lines = [
    "@prefix chorus: <https://jeffbridwell.com/chorus#> .",
    "@prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#> .",
    "@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .",
    "",
    "# GENERATED by service-harvest-gen.sh — never hand-edit (#3870).",
    f"# snapshot: {snap.get('harvestedAt','?')} · lastObserved stamp: {ts}",
    "",
]

seen = set()
for machine in sorted(snap.get("machines", {})):
    units = snap["machines"][machine]
    if not isinstance(units, dict) or "error" in units:
        continue
    for label in sorted(units):
        rec = units[label]
        if not isinstance(rec, dict):
            continue
        seen.add((machine, label))
        cls = "chorus:ScheduledJob" if rec.get("kind") == "job" else "chorus:ServiceInstance"
        lines.append(f"<urn:chorus:instance-{machine}-{label}>")
        lines.append(f"    a {cls} ;")
        lines.append(f'    rdfs:label "{esc(label)} ({machine})" ;')
        lines.append(f'    chorus:launchdLabel "{esc(label)}" ;')
        lines.append(f"    chorus:onMachine chorus:{machine} ;")
        if cls == "chorus:ServiceInstance":
            lines.append(f'    chorus:runState "{esc(rec.get("runState","loaded"))}" ;')
        bp = next((x for x in (rec.get("argv") or []) if x.startswith(OURS)), rec.get("program"))
        if bp:
            lines.append(f'    chorus:binaryPath "{esc(bp)}" ;')
        if label in mapping:
            lines.append(f"    chorus:runsService chorus:{mapping[label]} ;")
        if is_external(rec, label):
            lines.append('    chorus:external true ;')
        elif rec.get("evidenceUnavailable") and not is_ours(rec, label):
            # wren's third state: we could not look — an ops gap, its own
            # count; never "ours, unexplained" and never silently external.
            lines.append('    chorus:evidenceState "unknown" ;')
        lines.append(f'    chorus:lastObserved "{ts}"^^xsd:dateTime .')
        lines.append("")

# Vanish pass: instances in --previous absent from this snapshot keep their
# row flipped to runState "absent"; lastObserved keeps its OLD value (the
# truth: that is when it was last seen).
if prev_path:
    prev = open(prev_path).read()
    blocks = re.findall(r"<urn:chorus:instance-([a-z]+)-([^>]+)>(.*?)(?=\n<|\Z)", prev, re.S)
    for machine, label, body in blocks:
        if (machine, label) in seen:
            continue
        m = re.search(r'lastObserved "([^"]+)"', body)
        old_seen = m.group(1) if m else ts
        is_job = "ScheduledJob" in body
        cls = "chorus:ScheduledJob" if is_job else "chorus:ServiceInstance"
        lines.append(f"<urn:chorus:instance-{machine}-{label}>")
        lines.append(f"    a {cls} ;")
        lines.append(f'    rdfs:label "{esc(label)} ({machine})" ;')
        lines.append(f'    chorus:launchdLabel "{esc(label)}" ;')
        lines.append(f"    chorus:onMachine chorus:{machine} ;")
        if not is_job:
            lines.append('    chorus:runState "absent" ;')
        lines.append(f'    chorus:lastObserved "{old_seen}"^^xsd:dateTime .')
        lines.append("")

# Condition 1: stale mapping = LOUD. A label mapped but never observed gets a
# machine-written staleness row; the drift check reports it RED by name and it
# self-clears when the mapping is fixed or the unit returns.
observed_labels = {l for (_, l) in seen}
for label in sorted(set(mapping) - observed_labels):
    lines.append(f"<urn:chorus:mapping-stale-{label}>")
    lines.append("    a chorus:MappingStaleness ;")
    lines.append(f'    rdfs:label "stale mapping: {esc(label)} maps to {esc(mapping[label])} but no instance was observed" ;')
    lines.append(f'    chorus:launchdLabel "{esc(label)}" ;')
    lines.append(f'    chorus:lastObserved "{ts}"^^xsd:dateTime .')
    lines.append("")

open(out_path, "w").write("\n".join(lines) + "\n")
PYEOF
