#!/usr/bin/env bash
# werk-code-contract.sh — #3677: the checkable enforcement contract.
#
# werk-code's promise (werk-code-service-design.html): a rule about code either
# fires at a named pipeline moment with a negative fixture proving it goes red,
# or it is listed as prose and nobody mistakes it for protection. This checker
# makes that promise EXECUTABLE over platform/config/werk-code-contract.tsv:
#
#   STRUCTURE (exit 1 on violation):
#     - every row's moment is one of the six (the placement rule)
#     - a mechanism binds to exactly ONE moment (no duplicates)
#     - a non-GAP fixture path EXISTS on disk — a renamed/deleted fixture is a
#       loud red, never a silently-hollow contract row (#3734)
#   GAPS (reported, never hidden, never a failure by themselves):
#     - rows whose fixture is GAP print as the living gap-ledger
#
# Usage: werk-code-contract.sh [<root>]   exit 0 structure-clean / 1 violation

set -uo pipefail
ROOT="${1:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
TSV="$ROOT/platform/config/werk-code-contract.tsv"
[ -f "$TSV" ] || { echo "werk-code-contract: inventory missing at $TSV — the contract itself is gone (FAIL LOUD)" >&2; exit 1; }

MOMENTS="edit commit pipeline-test merge deploy-accept nightly"
violations=0; gaps=0; rows=0
seen=""

while IFS=$'\t' read -r mech moment fixture note; do
  case "$mech" in ''|'#'*) continue ;; esac
  rows=$((rows+1))
  case " $MOMENTS " in
    *" $moment "*) ;;
    *) echo "VIOLATION: $mech binds unknown moment '$moment' (placement rule: one of: $MOMENTS)"; violations=$((violations+1));;
  esac
  case " $seen " in
    *" $mech "*) echo "VIOLATION: $mech bound twice — a mechanism binds to exactly ONE moment"; violations=$((violations+1));;
  esac
  seen="$seen $mech"
  if [ "$fixture" = "GAP" ]; then
    gaps=$((gaps+1))
    echo "GAP: $mech ($moment) — no negative fixture: ${note:-unnamed}"
  elif [ ! -e "$ROOT/$fixture" ]; then
    echo "VIOLATION: $mech names fixture '$fixture' which does not exist — hollow contract row (#3734)"
    violations=$((violations+1))
  fi
done < "$TSV"

echo ""
echo "werk-code contract: $rows mechanisms · $((rows-gaps)) fixtures verified on disk · $gaps named gaps · $violations violations"

# Witness on the spine (#3677 AC4): the contract run is a recorded fact, not a
# terminal scroll. Best-effort — the verdict never depends on the emit.
LOG="$ROOT/platform/scripts/chorus-log"
if [ -x "$LOG" ]; then
  "$LOG" werk-code.contract "${DEPLOY_ROLE:-system}"     "mechanisms=$rows" "verified=$((rows-gaps))" "gaps=$gaps" "violations=$violations" >/dev/null 2>&1 || true
fi

# --update-ledger (#3677 AC5): regenerate the gap-ledger block in the design
# doc FROM this run's output — generated, never hand-edited.
if [ "${2:-}" = "--update-ledger" ]; then
  DOC="$ROOT/designing/docs/werk-code-service-design.html"
  if [ -f "$DOC" ]; then
    python3 - "$DOC" "$TSV" <<'PYEOF'
import sys, re, datetime
doc, tsv = sys.argv[1], sys.argv[2]
rows=[l.split('	') for l in open(tsv) if l.strip() and not l.startswith('#')]
gaps=[r for r in rows if len(r)>2 and r[2]=='GAP']
items=''.join(f"<li><code>{r[0]}</code> ({r[1]}) — {(r[3].strip() if len(r)>3 else 'unnamed')}</li>" for r in gaps)
block=(f"<!-- werk-code-gap-ledger:start (GENERATED by werk-code-contract.sh --update-ledger; do not hand-edit) -->"
       f"<p><strong>Live gap ledger</strong> — {len(gaps)} named gaps of {len(rows)} mechanisms, "
       f"regenerated {datetime.date.today().isoformat()} from platform/config/werk-code-contract.tsv:</p>"
       f"<ul>{items}</ul><!-- werk-code-gap-ledger:end -->")
s=open(doc).read()
if 'werk-code-gap-ledger:start' in s:
    s=re.sub(r'<!-- werk-code-gap-ledger:start.*?werk-code-gap-ledger:end -->', block, s, flags=re.S)
else:
    nl=chr(10)
    s=s.replace('</body>', block+nl+'</body>') if '</body>' in s else s+block
open(doc,'w').write(s)
print(f"gap ledger regenerated: {len(gaps)} gaps")
PYEOF
  fi
fi
[ "$violations" -eq 0 ] && exit 0 || exit 1
